### ISSUE TITLE
[FEATURE] Double logistic selectivity

### ISSUE THREAD

**Issue by JaneSullivan-NOAA** [NOAA-FIMS/FIMS#103]
**Is your feature request related to a problem? Please describe.**
Implement double logistic selectivity as described in Li et al. 2020 model comparison project

**Describe the solution you'd like**

Meeting date:  May 25 8-10 am AKT

Workflow:
- [x] Requirements gathering:  track down equation in Li et al. operating model. Add this equation to collaborative workflow document
- [x] Implementation:  create new branch, add new files and modify FIMS math as needed
- [x] Documentation:  generate new doxygen and supporting code documentation; make sure these are rendering correctly by building in powershell (`cmake -S . -B build -G Ninja` and `cmake --build build --parallel 16` and opening FIMS/build/html/index.html)
- [x] Write tests:  Follow the simple logistic example
- [x] Test the tests?  Maybe pull in Bai for help with this! `ctest --test-dir build`
- [x] Integration:  make sure all the proper `#include` statements are used
- [x] Internal review:  Check equations, documentation, formatting, then submit PR

**Describe alternatives you've considered**
Our directive is to reproduce the model comparison project.

**Describe a reference describing the statistical validity of this approach**
Our subgroup may determine that there are more statistically robust or flexible methods to implementing selectivity. We will compile these findings in a separate Issue. 

**Describe if this is needed for a management application**
N/A

**Additional context**
N/A

**Comment by ChristineStawitz-NOAA** [comment]
Removing triage_needed label since this is approved

**Comment by JaneSullivan-NOAA** [comment]
@Bai-Li-NOAA it's not clear to me which parameterization of the double-logistic selectivity you used in the [comparison paper](https://spo.nmfs.noaa.gov/sites/default/files/pdf-content/fish-bull/11923li.pdf).  Do you mind helping us figure out which equation to implement (or, you could just "AMAK style!"). Thanks for your help!
