### ISSUE TITLE
[FEATURE] add recruitment residuals and bias adjustment for beverton holt function

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS#106]
**Is your feature request related to a problem? Please describe.**
the existing recruitment module has a mean recruitment model but doesn't deal with deviations at all

**Describe the solution you'd like**
A vector of fixed effects that represent deviations from mean recruitment. Lognormal distribution?
[Edit]: More detail here: https://noaa-fims.github.io/collaborative_workflow/m1-model-specification.html#beverton-holt-expected-recruitment-function

**Describe alternatives you've considered**
Random effects for recruitment deviations will be implemented in the future but we need the fixed effects to compare to the model comparison output.

**Describe a reference describing the statistical validity of this approach**
[Hey look it's Ian's paper](https://cdnsciencepub.com/doi/full/10.1139/f2011-092?casa_token=Iw10Z_V1HegAAAAA%3AKMgydE_OvKBCSp-QQuF8k7ExzpqRQ54h_Qn-TFjeGVQFuqNj4OR5oDVtavXG9NMRB0WR0qoM_4Eb)

**Describe if this is needed for a management application**
This is common practice in tactical assessments.

**Additional context**

**Comment by Bai-Li-NOAA** [comment]
runningnotes : https://docs.google.com/document/d/1E_8YtzD9Ivd3-_uJ6JxeM0suGHnBVUyGHgRH0yFQvcg/edit?usp=sharing
