### ISSUE TITLE
[FEATURE] Pull TMB R-style distributions into FIMS objective function

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS#108]
**Is your feature request related to a problem? Please describe.**
`TMB` has already implemented many R-style statistical distributions in templated C++ functions that provide an atomic function. We need to pull them into the objective function and make sure they work which is not straightforward.

**Describe the solution you'd like**
Ability to use multinomial and normal distributions from `TMB` in FIMS objective function

**Describe alternatives you've considered**
We could implement the likelihoods ourselves within FIMS but this seems unnecessary unless we need to fit the model entirely outside of TMB someday

**Comment by Andrea-Havron-NOAA** [comment]
Summary of approach:
Create likelihoods.hpp file that calls FIMS-specific TMB likelihoods inline within a #ifdef TMB_MODEL header wrapper

Action Items:

- [ ] Set up feature branch for option 1

- [ ] Finalize and setup likelihoods.hpp file structure - need a likelihoods_base?

- [ ] Write DTMB_MODEL headers

- [ ] Write inline functions - are these within FIMS namespace?

- [ ] Write unit tests

- [ ] Write documentation

- [ ] Write integrated test using the logistic function from fims_math

[Running Notes](https://docs.google.com/document/d/1EEYvkyN8_LNxTMIHszOcbguwviyfPMgmV647pSXWTIk/edit)

[Link](https://github.com/NOAA-FIMS/FIMS/tree/108-feature-pull-tmb-r-style-distributions-into-fims-objective-function) to branch

[Example of inline TMB functions](https://github.com/Andrea-Havron-NOAA/FIMS-software/blob/83a54f46680f6ec550f1c7ff674ec56da8d52fc7/ModularTMBExamples/ar1xar1/Common.hpp#L49)

**Comment by Andrea-Havron-NOAA** [comment]
Action items for next meeting:

- [ ] Andrea will review structure with modeling team early next week
- Clarification questions:
  - Only list TMB functions we will use directly, cost of adding more?
  - Are inline functions set up correctly?

- Testing questions:
  - Fix bug in test: error that likelihoods/likelihoods.hpp is not found
  - Create multiple unit tests within one gtest file?
  - Test only files that have changed?
  - Create script to automatically update CMakeLists.txt?

- [ ] Address any issues with structure brought up by the modeling team
- [ ] Fix unit test for dnorm
- [ ] Develop unit test for dmultinom
- [ ] Develop benchmark tests for dnorm and dmultinom
- [ ] Add dlognorm function along with tests
- [ ] Documentation
