### ISSUE TITLE
[FEATURE] Non standard evaluation of function in input data frame

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [NOAA-FIMS/FIMS#111]
**Is your feature request related to a problem? Please describe.**
Need to pass Rfunction calls in a column of a data frame, e.g.,
```
myinputdata <- data.frame(
  numeric = 1:2,
  value = rnorm(2),
  functions = c(dnorm(value, 0, 1), dlnorm(value, 0, 1))
)

> myinputdata
  numeric     value    functions
1       1 0.4272809  dnorm(value, 0, 1)
2       2 0.5581573 dlnorm(value, 0, 1)
```
which leads to the following error because it is trying to evaluate functions
```
Error in dnorm(value, 0, 1) : object 'value' not found
```

**Describe the solution you'd like**
An easy, intuitive way to provide the two function calls in functions and NOT have them evaluated upon creating the data frame.

**Describe alternatives you've considered**

1. Use `quote()` around each function call.
2. Insert the function as a character string.
3. Pass the function name in one column and pass additional arguments in another column or using `...`.

**Additional context**
References for non-standard evaluation. Please feel free to edit this comment and lengthen the following list:
* [www.brodieg.com](https://www.brodieg.com/2020/05/05/on-nse/)
* [tidyverse programming](https://dplyr.tidyverse.org/articles/programming.html)

**Comment by Cole-Monnahan-NOAA** [comment]
Can you clarify what you want the element of myinputdata to be?

**Comment by Cole-Monnahan-NOAA** [comment]
I'm really behind on everything so excuse the naivete here, but you aren't ever going to actual evaluate those functions right? You're just specifying which likelihoods to use internally?

**Comment by kellijohnson-NOAA** [comment]
Exactly @Cole-Monnahan-NOAA, column 3 is for informational purposes only. I just thought that using the notation `dnorm(value, sd=1)` would make it really clear to users what function is being used behind the scenes to calculate a given portion of the likelihood and how the input value of 1 should be in terms of a standard deviation rather than CV or something else.
We also talked about using something more typical like
```
myinputdata <- data.frame(
  fleetname = "bestfleetever",
  value = rnorm(3),
  family = c(normal, lognormal, multinomial),
  uncertainty = c(1, 1, 100)
)
```
Where the uncertainty column would be specific to what is provided in "family". Here uncertainty would be sd, sdlog, and size in that order.

**Comment by Cole-Monnahan-NOAA** [comment]
Then at the risk of sounding grumpy, why do you need that fancy NSE stuff? You're not evaluating it. It's just a character string used as an instruction that is parsed later... right? 

I wonder if we could look to other software which uses R as a front end to gain some inspiration for how to specify distributions. For example 'brms' has syntax like:

````
prior_dye_brms <- c(set_prior("normal(0, 2000)", class = "Intercept"),
                    set_prior("cauchy(0, 50)", class = "sd"),
                    set_prior("cauchy(0, 50)", class = "sigma"))
dye_brms <- brm(Yield ~ 1 + (1 | Batch), data = lme4::Dyestuff, 
                prior = prior_dye_brms, chains = 0)
````

and 'rstanarm' looks like

````
my_prior <- normal(location = c(-10, 0), scale = c(5, 2))
stan_glm(y ~ x1 + x2, data = dat, prior = my_prior)
````

**Comment by kellijohnson-NOAA** [comment]
Thanks @Cole-Monnahan-NOAA and @k-doering-NOAA for the discussion. @Cole-Monnahan-NOAA you are right in that this is extra and not actually needed. I will look more at the `set_prior()` function and {rstanarm} package, as well as a package brought to my attention by @Andrea-Havron-NOAA called [{unmarked}](https://github.com/rbchan/unmarked).

# Conclusion

The input data frame will NOT need non-standard-evaluation but we might use it elsewhere in the user interface.
