### ISSUE TITLE
[FEATURE]: Use issue forms instead of issue templates for issue submission

### ISSUE THREAD

**Issue by k-doering-NOAA** [NOAA-FIMS/FIMS#126]
**Is your feature request related to a problem? Please describe.**
@kellijohnson-NOAA introduced me to [issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) yesterday, as opposed to issue templates. They seem much more user friendly to use because you can include drag down menus, etc. E.g., try out an example issue template by opening an issue in this testing repo: https://github.com/k-doering-NOAA/r.pkg.sandbox/issues/new/choose

**Describe the solution you'd like**
Change the [issue templates in the FIMS repo](https://github.com/NOAA-FIMS/FIMS/tree/main/.github/ISSUE_TEMPLATE) to issue forms

**Describe alternatives you've considered**
Leave as is.

**Describe a reference describing the statistical validity of this approach**
N/A

**Describe if this is needed for a management application**
N/A

**Additional context**
N/A

**Comment by k-doering-NOAA** [comment]
@ChristineStawitz-NOAA I would be happy to help with this. Feel free to assign me.

**Comment by ChristineStawitz-NOAA** [comment]
Thank you @k-doering-NOAA !
