### ISSUE TITLE
[BUG] repeats of fims::exp() and fims::log()

### ISSUE THREAD

**Issue by JaneSullivan-NOAA** [NOAA-FIMS/FIMS#137]
The exp() and log() functions are repeated twice in [fims_math](https://github.com/NOAA-FIMS/FIMS/blob/9b23fa8ee695fdddd079935704a37437ac4435f1/inst/include/common/fims_math.hpp#L36). Probably just a typo... happy to fix it if you want to assign it to me.

**Comment by ChristineStawitz-NOAA** [comment]
I don't think this is a bug actually..on line 21 the comment points out that the `IFDEF STD_LIB` and `IFDEF TMB_MODEL` are preprocessor directives that wrap each of the `exp` and `log` functions..so the first set of functions only gets run if the standard library is loaded and call `std:exp` while the second set only run if the model is being run within TMB and call the TMB exp function I believe. But, I am going to use this branch to do some other FIMS math cleanup
