### ISSUE TITLE
Update documentation in selectivity_base.hpp and selectivity/functor/logistic.hpp

### ISSUE THREAD

**Issue by JaneSullivan-NOAA** [NOAA-FIMS/FIMS#144]
The description of the [selectivity_base.hpp](https://github.com/NOAA-FIMS/FIMS/blob/bb09c7b6aeb7ab815f48f320d9e211b6a9bbdb31/inst/include/population_dynamics/selectivity/functors/selectivity_base.hpp#L7) files is copied/repeated from selectivity.hpp and should probably be updated to something like:

```
* selectivity_base.hpp
* The purpose of this file is to declare the SelectivityBase class
* which is the base class for all selectivity functors.
```

It also looks like the documentation for selectivity_base was put in the [logistic ](https://github.com/NOAA-FIMS/FIMS/blob/bb09c7b6aeb7ab815f48f320d9e211b6a9bbdb31/inst/include/population_dynamics/selectivity/functors/logistic.hpp#L6)functor for selectivity.

I recommend reviewing and updating the selectivity module documentation.

**Comment by ChristineStawitz-NOAA** [comment]
See linked PR for the added documentation
