### ISSUE TITLE
[BUG] `clang-tidy` workflow fails

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS#15]
**Describe the bug**
I can't tell if this is an issue with the files or the workflow .yml but I noticed the clang-tidy github action is failing (on both issue #9  and #10 . I thought it was because we didn't have any C++ code but now we do. Needs further investigation.

**To Reproduce**
1. Make some changes
2. Submit pull request
3. See clang-tidy workflow has failed

**Expected behavior**
clang-tidy workflow passes

**Desktop (please complete the following information):**
 - OS: not specific - occurs in GH actions

**Additional context**

**Comment by k-doering-NOAA** [comment]
It looks like this is the problem: https://github.com/NOAA-FIMS/FIMS/runs/5457154658?check_suite_focus=true#step:4:9

I guess too old of a version of cmake is being used?

**Comment by k-doering-NOAA** [comment]
Ok, I think I understand it now. We say the minimum cmake version must be 3.20 in our CMakeLists.txt file, but the github action is running 3.16.3. I think one fix would be to change the cmake minimum version to 3.16; the other option is to find a different workflow. @Bai-Li-NOAA , do you think changing the minimum cmake version would be ok? That seems easier...

**Comment by Bai-Li-NOAA** [comment]
@k-doering-NOAA, I agree, changing minimum CMake version probably would be a easer fix. I think we can use cmake_minimum_required(VERSION 3.14) after looking at GoogleTest examples.

I am also not sure about the `section` in the Clang-tidy workflow:
```
with:
        scandir: '.'
        builddir: 'build'
        excludedirs: ''
        extensions: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'
        cmakeoptions: ''
```

Maybe we need to change the scan directory to inst/include and src/? I know build/ is under .gitignore.

**Comment by Bai-Li-NOAA** [comment]
I created a [bug-issue-15-clang-tidy](https://github.com/NOAA-FIMS/FIMS/tree/bug-issue-15-clang-tidy-workflow) branch for us to work on this issue. The workflow runs successfully after changing CMake required version and the workflow build trigger, please see details in the [log](https://github.com/NOAA-FIMS/FIMS/actions/runs/1960163507). 

However, I do not think the workflow does what we wanted or maybe we did not set it up correctly?
- I went to the action repo and looked at their [.clang-tidy checks](https://github.com/HorstBaerbel/action-clang-tidy/blob/master/.clang-tidy). I picked -cppcoreguidelines-avoid-magic-numbers to test it.
- I injected some [bad code](https://clang.llvm.org/extra/clang-tidy/checks/readability-magic-numbers.html) from clang-tidy documentation that is supposed to introduce the magic numbers to the code inside of inst/internal and gtest/ folders. 
- The clang-tidy workflow still ran successfully and thought all code was fine even though the googleTest failed to compile. 

To move forward, I think we could
1) try modify settings in the current workflow (do not know how yet) or
2) try other workflows, or
3) write a workflow from scratch: install actual clang-tidy and then run checks that are related to FIMS
