### ISSUE TITLE
[Bug]: testthat test-use-module.R does not work on GHA

### ISSUE THREAD

**Issue by Bai-Li-NOAA** [NOAA-FIMS/FIMS#160]
### Describe the bug

The FIMS/tests/testthat/test-use-module.R works locally when running devtools::test() but it does not work when running devtools::check() loacally and when running call-r-cmd-check and call-calc_coverage GHA workflows.

### To Reproduce

To run it locally, we can use devtools::test(), and the tests pass.
When running the tests through GHA workflows, the [error message from call-r-cmd-check](https://github.com/NOAA-FIMS/FIMS/runs/6582509223?check_suite_focus=true#step:9:108) was:
```
Error in `setwd(subdir)`: cannot change working directory
```

The [error message from call-calc_coverage](https://github.com/NOAA-FIMS/FIMS/runs/6582507206?check_suite_focus=true#step:8:11) was:
```
Error: Failure in `/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Rtmp3eJ13e/R_LIBSc282330f1ab/FIMS/FIMS-tests/testthat.Rout.fail`
Error in `setwd(subdir)`: cannot change working directory
```

### Expected behavior

Both devtools::test() and devtools::check() should work locally

### Which OS are you seeing the problem on?

Windows, Mac, Linux

### Which version of FIMS are you seeing the problem on?

0.0.0.9

### Additional Context

I wonder if we could avoid using setwd() in the [use_module R function](https://github.com/NOAA-FIMS/FIMS/blob/main/R/use_module.R).
@k-doering-NOAA, have you seen similar issues when writing R functions for ghactions4r or r4ss? Or do you have any suggestions about how to set the working directory inside of an R function or R test? Thank you!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by k-doering-NOAA** [comment]
I think the easiest solution would just be to use the relative path throughout without resetting the working directory. However, we definitely reset the working directory when running stock synthesis in e.g., [`r4ss::run_SS_models()`](https://github.com/r4ss/r4ss/blob/03ea31db712125f7f9b8617935f1491ee171bddb/R/run_SS_models.R#L129) and this function runs during the test on github actions. So I don't think `setwd()` always fails on github actions? It might be something specific about the way this test or function is set up?

**Comment by Bai-Li-NOAA** [comment]
Thanks, @k-doering-NOAA. Agree, I am working on using relative paths in the R function instead of resetting the working directory.

Also found out that devtools::test() and devtools::check() use different testing environments and different folder structures. We can find the `FIMS/inst/include` folder when running devtools::test() locally, while `FIMS/include` when running devtools::check(). So using the if else statement to create different paths under different situations helped resolve the issue.

```
if (!file.exists(file.path(project_path, "inst"))){
      path <- file.path("include", "population_dynamics")
  } else {
      path <- file.path("inst", "include", "population_dynamics")
  }
```
