### ISSUE TITLE
[FEATURE] logistic selectivity module

### ISSUE THREAD

**Issue by Andrea-Havron-NOAA** [NOAA-FIMS/FIMS#17]
**Is your feature request related to a problem? Please describe.**
The logistic selectivity module is a requirement for Milestone 1 of the FIMS implementation plan.

**Describe the solution you'd like**
A selectivity_base class that calls a logistic selectivity function. The logistic function should be defined separatly in a fims_math.hpp module.  Any additional structure in the FIMS package needs to be developed in order to call and implement this module from R.

**Describe alternatives you've considered**
We have considered implementing logistic selectivity within a standalone C++ or TMB model.

**Describe a reference describing the statistical validity of this approach**
This module is defined as a requirement for [Milestone 1](https://noaa-fims.github.io/collaborative_workflow/m1-model-specification.html#logistic-function-with-extensions).

**Describe if this is needed for a management application**
The logistic selectivity function is frequently used in catch-at-age stock assessment models to describe the proportion of fish captured by size of age.

**Additional context**
n/a

**Comment by msupernaw** [comment]
It's implemented here. logistic_selectivity calls fims_math::logistic.

https://github.com/NOAA-FIMS/software_arch/blob/main/fims/include/population_dynamics/selectivity/functors/logistic.hpp#L52

**Comment by Andrea-Havron-NOAA** [comment]
Thanks @msupernaw, I'll work on copying files over.
