### ISSUE TITLE
[Refactor]: wrap Rcpp_interface add_to_tmb functions in ifdef statements 

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS#171]
### Refactor request

We need to ensure objects aren't added to the TMB model unless a TMB model is defined

### Expected behavior

Only add to TMB model if running via TMB

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Andrea-Havron-NOAA** [comment]
part of PR#459
