### ISSUE TITLE
[Feature]: Develop fleet module

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS#179]
### Is your feature request related to a problem? Please describe.

A way to define each fleet and survey and associate it with the relevant data, likelihood, and selectivity function.

### Describe the solution you would like.

Fleet class which contains members and methods associated with fishing fleets and research surveys. 

- [x] id member
- [x] index data
- [x] age comp
- [ ] length comp
- [ ] calculate catch methods

### Describe alternatives you have considered

We could put some of the fleet calculations in population.hpp

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ChristineStawitz-NOAA** [comment]
branch here https://github.com/NOAA-FIMS/FIMS/tree/feature-fleet-module

**Comment by Andrea-Havron-NOAA** [comment]
Where is the best place to sum the negative log-likelihoods? Currently, the age comp and index log-likelihoods are summed within the fleet module. Two issues were raised:

- consistent nomenclature is needed: terms 'negative log-likelihood' or 'log-likelihood' should be used to reflect how the likelihood is being called and defined
- should likelihoods be summed in the fleet module or in model.hpp? It would be preferred to have all likelihoods in one place so it is clear how they are being pulled together. Additionally, the team discussed how it will be useful to access likelihood components at the scale of the observation to improve model diagnostics and validation

**Comment by iantaylor-NOAA** [comment]
Some likelihood contributions, like the [recruitment likelihood](https://github.com/NOAA-FIMS/FIMS/blob/main/inst/include/population_dynamics/recruitment/functors/recruitment_base.hpp#L110-L131), are not associated with any fleet. 

Our requirements spreadsheet includes "[Likelihood for each datum: ability to include observations at lowest level possible?](https://docs.google.com/spreadsheets/d/1i9zws9pk1fZ7D8RLrGH2CN7QU48ij86oOY_XgwaG7n4/edit#gid=591354523)" This is in line with the second bullet above. That suggests to me that the individual modules could be populating a new column in the table of observed input data (also perhaps expected values) and the summation could occur at the end, outside of the fleet modules.

**Comment by nathanvaughan-NOAA** [comment]
Thanks Ian, that is inline with our group discussions. I like the idea of appending the likelihoods to the input data frame, maintaining observed values, expected values, and likelihoods in a single data frame should make interaction with these much easier in future model updates. Also including bootstrapped data values in this table would be helpful when this functionality is available.

**Comment by Andrea-Havron** [comment]
- [ ] Resolve r cmd check errors

**Comment by Andrea-Havron** [comment]
To Do:

- [ ] Rcpp and testing (check with modeling team)

**Comment by Bai-Li-NOAA** [comment]
Hi fleet module team, the Rcpp team is working on developing an R test for the fleet interface. The R test failed due to an [ID checking error](https://github.com/NOAA-FIMS/FIMS/issues/193#issuecomment-1212349915), will fix the error on this branch once we find a solution for it.
