### ISSUE TITLE
[Feature]: Develop population loop module

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS#180]
### Is your feature request related to a problem? Please describe.

We need to connect all the FIMS modules together and loop through to calculate biomass and other quantities.

### Describe the solution you would like.

A population class which includes all the methods for calculating quantities in the population.

- [ ] id member
- [ ] initial conditions method
- [ ] calculate N at age
- [ ] calculate catch
- [ ] calculate recruitment

### Describe alternatives you have considered

putting all these calculations in model.hpp which is less modular

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Andrea-Havron-NOAA** [comment]
branch: [180-feat-population](https://github.com/NOAA-FIMS/FIMS/tree/180-feat-population)

**Comment by Andrea-Havron-NOAA** [comment]
Discussion:

What is the best way to set up a generic population loop that allows for easy extensibility in future milestones? Is it possible to loop through the population without explicitly stating what is being looped over (ie. years, seasons, areas)?

@nathanvaughan-NOAA also brought up the point that it is inefficient to loop through every possible combination of population partitions. Can we simplify this by calculating expected values of the population at the same resolution as our data observations? This would mean time steps between expected values are not equidistant. What would be the implications in this approach to biological calculations (ie. recruitment, growth)?

**Comment by Andrea-Havron** [comment]
To Do:
Develop population loop in Information.hpp

- [ ] Loop through [population iterator](https://github.com/NOAA-FIMS/FIMS/blob/af5d0e5b801a5ba698c7ef0f998d347fb2d33ce6/inst/include/common/information.hpp#L225)
  - [ ] Add growth model
  - [ ] Add recruitment model

**Comment by k-doering-NOAA** [comment]
We started working on the life history calculations in the [Evaluate() loop](https://github.com/NOAA-FIMS/FIMS/blob/58f176357823955d3a987f838c239f46ca8526ba/inst/include/population_dynamics/population/population.hpp#L134-L164). Still partially finished. We plan to continue working on this next time our group meets, and will look to SAM and WHAM as additional inspiration for writing this section (in addition to rMAS and RASAMS)
