### ISSUE TITLE
[Test]: Write more C++ and R tests and reschedule codecov GHA 

### ISSUE THREAD

**Issue by Bai-Li-NOAA** [NOAA-FIMS/FIMS#182]
### Is your feature request related to a problem? Please describe.

- The current code coverage of FIMS is 27%. After checking individual files, we need to add more C++ and R tests.
- The current codecov GHA runs everyday at 5:30 pm, which means developers and code reviewers may not know whether they need to write more tests because they could not see the latest codecov report when submitting/merging a pull request. That means we always need to periodically review individual files on the codecov website and find a group of people to write ad hoc tests after merging in the code to the main branch. 

### Describe the solution you would like.

we need to add more tests for following files:
C++ tests:

- [x] [lines 141-173 in inst/include/common/fims_math.hpp](https://app.codecov.io/gh/NOAA-FIMS/FIMS/blob/main/inst/include/common/fims_math.hpp) (75%)
- [ ] check the reason why codecov ignore tests/gtest/test_sr_beverton_holt.cpp

R tests:

- [x] [R/create_rcpp_interface_object.R](https://app.codecov.io/gh/NOAA-FIMS/FIMS/blob/main/R/create_rcpp_interface_object.R) (0%)
- [ ] [R/io.R](https://app.codecov.io/gh/NOAA-FIMS/FIMS/blob/main/R/io.R) (0%)
- [x] [R/use_module.R](https://app.codecov.io/gh/NOAA-FIMS/FIMS/blob/main/R/use_module.R) (91.3%)
- [x] R/fimsfram.R (65.12%)
- [x] R test for [rcpp_selectivity.hpp](https://github.com/NOAA-FIMS/FIMS/blob/main/inst/include/interface/rcpp/rcpp_objects/rcpp_selectivity.hpp)
- [x] R test for [rcpp_recruitment.hpp](https://github.com/NOAA-FIMS/FIMS/blob/main/inst/include/interface/rcpp/rcpp_objects/rcpp_recruitment.hpp)

To reschedule codecov GHA, it might be easier to just run codecov for every push & pull request on the main branch, so developers and code reviewers could check codecov and write a good coverage of tests before merging in a pull request.

### Describe alternatives you have considered

None

### Statistical validity, if applicable

None

### Describe if this is needed for a management application

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by k-doering-NOAA** [comment]
> The current codecov GHA runs everyday at 5:30 pm, which means developers and code reviewers may not know whether they need to write more tests because they could not see the latest codecov report when submitting/merging a pull request. That means we always need to periodically review individual files on the codecov website and find a group of people to write ad hoc tests after merging in the code to the main branch.

This is a good point! Maybe we should change the build trigger to being on pull request to the main branch rather than scheduling it?

**Comment by Bai-Li-NOAA** [comment]
Agree, @k-doering-NOAA. I think changing the build trigger to being on pull request to the main branch will help. I can also test if we can keep the 5:30pm GHA runs in addition to running the GHA on pull request.

**Comment by k-doering-NOAA** [comment]
@Bai-Li-NOAA , it should be possible to do both! Let me know if you would like any help modifying the build triggers.

**Comment by Bai-Li-NOAA** [comment]
Great, thanks, @k-doering-NOAA! Please feel free to modify the build trigger on the linked branch (https://github.com/NOAA-FIMS/FIMS/tree/182-test-write-more-c%2B%2B-and-r-tests-and-reschedule-codecov-gha).

I will work on improving code coverage.

**Comment by k-doering-NOAA** [comment]
> Great, thanks, @k-doering-NOAA! Please feel free to modify the build trigger on the linked branch (https://github.com/NOAA-FIMS/FIMS/tree/182-test-write-more-c%2B%2B-and-r-tests-and-reschedule-codecov-gha).
> 
> I will work on improving code coverage.

Ok, I added a build trigger so code coverage runs when a pull request is opened to main also.

**Comment by Bai-Li-NOAA** [comment]
@k-doering-NOAA, Thanks for making the changes! I will make a pull request to merge the changes to main and then working on other testing issues.

**Comment by k-doering-NOAA** [comment]
@Bai-Li-NOAA, I noticed I am an assignee on this. Not sure if you wanted help on my end?

**Comment by Bai-Li-NOAA** [comment]
@k-doering-NOAA, I think you were assigned to modify the build trigger in the code cov GHA and you have fixed it! However, I found a new code cov issue and I have not been able to solve the problem. 

Sometimes, the code cov value on the FIMS repo does not match the real value on code cov website. The value on the FIMS repo was 94% yesterday and it changed to [45%](https://github.com/NOAA-FIMS/FIMS) today. According to the code cov website, it is supposed to be [94%](https://app.codecov.io/gh/NOAA-FIMS/FIMS?branch=main).

Also, the code cov only scans the C++ tests for some reason and excludes R tests. I am curious if you have experience with it.

**Comment by k-doering-NOAA** [comment]
@Bai-Li-NOAA , hmmm, interesting, thanks for reporting this! I've actually only used code cov for r tests and not c++, but I can try to take a look understand what it's doing.
