### ISSUE TITLE
[Bug]: Error in Google test GHA when CXX compiler is GNU 11.2.0

### ISSUE THREAD

**Issue by Bai-Li-NOAA** [NOAA-FIMS/FIMS#183]
### Describe the bug

[One of the gtest GHAs is failing for TMB r style distributions group](https://github.com/NOAA-FIMS/FIMS/pull/181). The error message is

```
CMake Error at build/_deps/googlebenchmark-src/CMakeLists.txt:283 (message):
61-- Performing Test HAVE_POSIX_REGEX -- failed to compile
62 Failed to determine the source files for the regular expression backend
```
For the failed GHA run, the CXX compiler is GNU 11.2.0. The successful GHA runs in the past use GNU 8.1.0. Fixing the compiler version in GHA may help resolve the issue.

### To Reproduce

The GHA log can be found [here](https://github.com/NOAA-FIMS/FIMS/runs/7042227927?check_suite_focus=true)

### Expected behavior

I expected the Google tests GHA passes on Windows.

### Which OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bai-Li-NOAA** [comment]
There are two potential solutions:
1. Change GitHub Actions virtual environment from windows-latest to windows-2019. It worked and successful GHA run can be found [here](https://github.com/NOAA-FIMS/FIMS/runs/7097678645?check_suite_focus=true)

GitHub Actions has updated its windows-latest virtual environment. [The windows-latest (Windows2022) contains Mingw-w64 11.2.0](https://github.com/actions/virtual-environments/blob/releases/win22/20220626/images/win/Windows2022-Readme.md). It returns an error in GHA log  when HAVE_GNU_POSIX_REGEX and HAVE_POSIX_REGEX fail to compile. If we use windows-2019, it contains [Mingw-w64 8.1.0](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md), which does not fail the GHA run when HAVE_GNU_POSIX_REGEX and HAVE_POSIX_REGEX fail to compile. 

2. Add following compilation flags when running cmake based on [Google Benchmark suggestions](https://github.com/google/benchmark/issues/351). However, the FIMS GHA is still [failing](https://github.com/NOAA-FIMS/FIMS/runs/7097678551?check_suite_focus=true) after using those flags. May need to submit an issue to Google benchmark to get some advice.
```cmake
-DCMAKE_CROSSCOMPILING=1 -DRUN_HAVE_STD_REGEX=0 -DRUN_HAVE_POSIX_REGEX=0 -DRUN_GNU_POSIX_REGEX=0
```

**Comment by Bai-Li-NOAA** [comment]
Reopen the issue to continue exploring solution 2.

**Comment by Andrea-Havron-NOAA** [comment]
Status of this issue?

**Comment by Bai-Li-NOAA** [comment]
@Andrea-Havron-NOAA I can check if GNU 11.2.0 works during MQ.
