### ISSUE TITLE
[FEATURE] use issue-group notation for some labels

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [NOAA-FIMS/FIMS#19]
**Is your feature request related to a problem? Please describe.**
It is unclear what labels are seen are part of a group of labels making it difficult to know which labels you should be adding to a new issue other than the ones that are automatically assigned. For example, collaborative workflow references "kind" and "state" as two types of labels that you should assign to a new issue but it is unclear from just looking at the labels which ones are options that I can choose from when assigning a state.

**Describe the solution you'd like**
I would like labels to be renamed if they are part of a group of labels. E.g., kind: bug kind: enhancement

**Describe alternatives you've considered**
I think we could also add notation to declare if you should only select one of the options within a group or if many selections are okay. For example, `kind(+): bug` and `kind(+): question` vs `status(1): won't fix` `status(1): urgent` could work but is not standard. Maybe colors would be a better way but then you would have to remember what the colors mean and it wouldn't list labels within a group near each other b/c label lists are alphabetized. I typically just use colors to reiterate the group. Must be a learned behavior because I work under Hastie who loves to use colors.

We could also just use the description box to enter this information because when you are creating an issue you can read the descriptions when you select "Labels".

**Describe a reference describing the statistical validity of this approach**
NA

**Describe if this is needed for a management application**
NA

**Additional context**
I realize this is a very trivial issue and really doesn't matter. So, feel free to close and I will just read collaborative workflow for guidance when I forget.

**Comment by k-doering-NOAA** [comment]
I think only people that have write access to the repo can add labels, also. Maybe if the triage_needed label is assigned automatically, we could have someone from the FIMS team designated to take a look at the issues with this label as they come in and add the other appropriate labels? Maybe this is already part of the workflow.

**Comment by ChristineStawitz-NOAA** [comment]
thanks for the suggestion! I tried to do this with three different issue types: attribute, status, and kind, with the thinking that attribute is the only one that can have multiple labels from the same category. let me know if this is unclear!
