### ISSUE TITLE
[Feature]: Rcpp interface to call module, likelihoods

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS#193]
### Is your feature request related to a problem? Please describe.

Continue fleshing out the `Rcpp` interface for sprint 3. 

### Describe the solution you would like.

Right now it is implemented for the modules but we need to expose the model class and affiliate it with all of the modules and then create a way to run the TMB model in R.

### Describe alternatives you have considered

We could expose only the modules and call the TMB compile function directly but this makes it difficult to manipulate subpopulations and parameter values in R.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Andrea-Havron-NOAA** [comment]
Good question @Bai-Li-NOAA. The collaborative workflow document for M1 specifies the [multinomial](https://noaa-fims.github.io/collaborative_workflow/m1-model-specification.html#likelihood-calculations) will be used for the agecomp likelihoods, so x will be catch-at-age and p will be expected catch-at-age. Both are derived so I think you are correct that x and p do not need to be registered at this time.

**Comment by Bai-Li-NOAA** [comment]
Do we need to add error checking/input validation for all module IDs? FIMS [code](https://github.com/NOAA-FIMS/FIMS/blob/9d996e2328a7c90a069f914cc3935a4137a77b3f/tests/testthat/test-fleet.R#L25) does not throw an error when user set an non-integer ID (e.g. 1.2) for selectivity of fleet accidentally and the [failed R test can be found here](https://github.com/NOAA-FIMS/FIMS/runs/7793087002?check_suite_focus=true#step:9:230). Maybe FIMS converts the non-integer value to an integer value internally?

**Comment by Andrea-Havron-NOAA** [comment]
C++ will inplicitly convert a float to an integer ([see example](https://noaa-fims.github.io/TMB_training/2022_TMB_Session_I/docs/00_Likelihoods_AD.html#12)). 

I don't think users will actually be setting these IDs, aren't they internally assigned within FIMS?

**Comment by Bai-Li-NOAA** [comment]
Great example, thanks!

Users won't need to set the IDs once we have wrapper functions to use the formula interface, but for M1, I think users need to [set a few IDs for the fleet module](https://github.com/NOAA-FIMS/FIMS/blob/9d996e2328a7c90a069f914cc3935a4137a77b3f/inst/include/interface/rcpp/rcpp_interface.hpp#L83) if there are no wrapper functions to assign ID internally. For example, fleet$SetSelectivity(id), fleet$SetObservedIndexData(id), etc.
