### ISSUE TITLE
Tests lead to pdf file

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [NOAA-FIMS/FIMS#208]
https://github.com/NOAA-FIMS/FIMS/blob/cd447812d71ab3635460ba88dc5c6918392e8854/tests/testthat/test-fimsframe.R#L14-L15

These lines of code led to Rplots.pdf which was incorrectly pushed to FIMS. Should we just `git rm` it or remove it from all history which is slightly difficult with the number of branches that we have.

**Comment by ChristineStawitz-NOAA** [comment]
We should `git rm` it and also add some code to delete the file after the test runs so we clean up after the test.

**Comment by Bai-Li-NOAA** [comment]
Hi @kellijohnson-NOAA , in addition to removing the existing PDF file, a [helper function](https://github.com/NOAA-FIMS/FIMS/blob/5f4d4926d7624d5cb3ab0b8c7431ab73c7f06992/tests/testthat/test-fimsframe.R#L16) is now included in the test and the function creates a temporary figure outside the FIMS working folder.

The helper function is from the [testthat expect_snapshot_file()](https://testthat.r-lib.org/reference/expect_snapshot_file.html) example. The expect_snapshot_file() function can help test images by comparing images from future runs with the reference image. If the images are different, the test will fail. Do you want to have a full image comparison here so the FIMs test will fail when the data_mile1 data have been changed? If yes, I can add a test to compare the images. If not, I plan to create a pull request based on current code changes.

**Comment by kellijohnson-NOAA** [comment]
Currently, or maybe even ever, I do not think that we need to actually compare the contents of the file. When I created the test, the intent was just to make sure that the figure was created without warnings. I was delaying working on this because I think that the file should not be just removed from the repository but the history of it should also be removed, which is difficult to do when there are a lot of branches. Leaving large files like this in the repository makes it take longer to clone. I know it is just one file and maybe I am overthinking things 🤷.

**Comment by Bai-Li-NOAA** [comment]
Great point on cleaning the history. I will make sure the PDF file is
removed from the history and then make a pull request from there.

**Comment by k-doering-NOAA** [comment]
will rewriting the history mess up branches, though? I also think you would have to push the change to main directly, as otherwise the history would remain, I think?

I get Kelli's point, but I think it is a little risky/unorthodox to change the history, especially when there is a lot of in progress work. Maybe we could note this as something for Milestone Q when there isn't any partially done work, and then the repo changes for everyone?

**Comment by Bai-Li-NOAA** [comment]
Yes, @k-doering-NOAA, you are right about the effects on feature branches. I plan to fork the repo and test it from there, but it's probably better to do it during Milestone Q as you suggested. I think we can just git rm the file for now and make a pull request, then clean the history during Milestone Q.
