### ISSUE TITLE
[Bug]: Need to add FimsFrame documentation

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS#209]
### Describe the bug

We need to update the `DESCRIPTION` and `NAMESPACE` fields of the package to work with FimsFrame

### To Reproduce

Run `devtools::check`
See the following warnings:
`Consider adding
  importFrom("methods", "new", "slot", "slotNames")
  importFrom("utils", "head")
to your NAMESPACE file (and ensure that your DESCRIPTION Imports field
contains 'methods').`

### Expected behavior

no warnings

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by k-doering-NOAA** [comment]
Looking at these warnings again, it looks like calling methods:: or utils:: in front of the function calls is one solution (the other one would be to use @import or @importFrom within the documentation for each functino that uses one of these function calls.
