### ISSUE TITLE
[Bug]: FIMS.o: too many sections. Add flag to solve?

### ISSUE THREAD

**Issue by k-doering-NOAA** [NOAA-FIMS/FIMS#213]
### Describe the bug

Setting up my new computer, I couldn't get the main branch of FIMS to compile using `devtools::load_all(".")`. I found that adding a additional flag `-Wa,-mbig-obj` to the PKG_CXXFLAGS line in Makevars.win allowed FIMS to compile just fine on my computer. This is the resource that lead me to add the flag: https://digitalkarabela.com/mingw-w64-how-to-fix-file-too-big-too-many-sections/

I am wondering if anyone else has encountered this, and how I should deal with this issue? I don't know if the solution I came up with should be pushed up to the FIMS repo, or if there is some other place I should put the flag? It sounds like this is specific to the mingw-w64 compiler...

### To Reproduce

This is the output I get when running devtools::load_all("."):

```r
r$> devtools::load_all(".")
i Loading FIMS
Re-compiling FIMS
-  installing *source* package 'FIMS' ... (342ms)
   ** using staged installation
   ** libs
   g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-42~1.1/include" -DNDEBUG  -I'C:/Users/Kathryn.Doering/AppData/Local/R/win-library/4.2/Rcpp/include' -I'C:/Users/Kathryn.Doering/AppData/Local/R/win-library/4.2/TMB/include' -I'C:/Users/Kathryn.Doering/AppData/Local/R/win-library/4.2/RcppEigen/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -DTMB_MODEL  -DTMB_EIGEN_DISABLE_WARNINGS   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -UNDEBUG -Wall -pedantic -g -O0 -fdiagnostics-color=always -c FIMS.cpp -o FIMS.o      
   as: FIMS.o: too many sections (35851)
   C:\Users\KATHRY~1.DOE\AppData\Local\Temp\ccysMZMJ.s: Assembler messages:
   C:\Users\KATHRY~1.DOE\AppData\Local\Temp\ccysMZMJ.s: Fatal error: can't write 326 bytes to section .text of FIMS.o: 'file too big'
   as: FIMS.o: too many sections (35851)
   C:\Users\KATHRY~1.DOE\AppData\Local\Temp\ccysMZMJ.s: Fatal error: FIMS.o: file too big
   make: *** [C:/PROGRA~1/R/R-42~1.1/etc/x64/Makeconf:260: FIMS.o] Error 1
   ERROR: compilation failed for package 'FIMS'
-  removing 'C:/Users/KATHRY~1.DOE/AppData/Local/Temp/Rtmpmmxtfn/devtools_install_4ba87ea9282f/FIMS'
Error in `(function (command = NULL, args = character(), error_on_status = TRUE, ...`:
! System command 'Rcmd.exe' failed
---
Exit status: 1
stdout & stderr: <printed>
---
Type .Last.error to see the more details.

```

### Expected behavior

FIMS to compile

### Which OS are you seeing the problem on?

Windows

### Which version of FIMS are you seeing the problem on?

main branch 

### Additional Context

Using rtools42 and R 4.2.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Andrea-Havron-NOAA** [comment]
I've run into this problem with a TMB model before. From what I've learned, some of these devtools commands turn the debugger back on, which adds bloat to the .o file. Compare your flags to the compilation flags listed under one on the [GHAs](https://github.com/NOAA-FIMS/FIMS/runs/7774567882?check_suite_focus=true#step:9:80) up on FIMS:

```
g++  -std=gnu++11 -I"C:/R/include" -DNDEBUG  -I'D:/a/_temp/Library/Rcpp/include' 
-I'D:/a/_temp/Library/TMB/include' -I'D:/a/_temp/Library/RcppEigen/include'  
-I"c:/rtools42/x86_64-w64-mingw32.static.posix/include"  -DTMB_MODEL  
-DTMB_EIGEN_DISABLE_WARNINGS   -O2 -Wall  -mfpmath=sse -msse2 
-mstackrealign  -c FIMS.cpp -o FIMS.o 
```


The compilation flags you listed above have the additional flags: `-UNDEBUG -Wall -pedantic -g -O0 -fdiagnostics-color=always` The [-g flag](https://bytes.usc.edu/cs104/wiki/gcc/) is for the g++ debugger

`devtools::load_all(".")` can also be inefficient as it loads all functions regardless if they are exported to namespace. Should we be using `devtools::install()` or `remotes::install_github("NOAA-FIMS/FIMS")` instead?

**Comment by k-doering-NOAA** [comment]
Thanks @Andrea-Havron-NOAA! I tried `devtools::install()` and you are right that it worked just fine! I'll just modify my typical development workflow :) Also, I added a note to the collaborative workflow document that devtools::install() should be used rather than devtools::load_all() (https://github.com/NOAA-FIMS/collaborative_workflow/commit/ed0ec8f9178cd11cc325a8f78570f0af7af79e06)

**Comment by k-doering-NOAA** [comment]
Just noting that `devtools::document()` seems to run `devtools::load_all()` before updating the documentation. Not sure if there is an alternative so I can avoid adding the `-Wa,-mbig-obj` flag?

**Comment by Andrea-Havron-NOAA** [comment]
I usually run `roxygen2::roxygeniz()` directly. Is there an additional benefit to running `devtools::document()`?

**Comment by k-doering-NOAA** [comment]
I think devtools::document is exactly the same as roxygen2::roxygenize(); I tried roxygen2::roxygenize and still ran into the need to add the flag.
