### ISSUE TITLE
[Refactor]: Refactor values, min, max, and estimated from the Parameter constructor

### ISSUE THREAD

**Issue by Bai-Li-NOAA** [NOAA-FIMS/FIMS#218]
### Refactor request

We could refactor the names from the [lines 56-57 of the rcpp_interface_base.hpp](https://github.com/NOAA-FIMS/FIMS/blob/main/inst/include/interface/rcpp/rcpp_objects/rcpp_interface_base.hpp#L56:~:text=Parameter(double,max)%2C%20estimated(estimated)%20%7B%7D) to make them clearer. For example, from  
```c++
Parameter(double value, double min, double max, bool estimated)
      : value(value), min(min), max(max), estimated(estimated) {}
```
to
```c++
Parameter(double value_m, double min_m, double max_m, bool estimated_m)
      : value(value_m), min(min_m), max(max_m), estimated(estimated_m) {}
```

@msupernaw suggests we refactor relevant code during the MQ stage.

### Expected behavior

Use different names to distinguish values, min, max, and estimated from the Parameter constructor.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Andrea-Havron-NOAA** [comment]
Related to Issue #411
