### ISSUE TITLE
[Feature]: Automatically delete branches that have been merged

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [NOAA-FIMS/FIMS#219]
### Is your feature request related to a problem? Please describe.

There are currently 2 branches that have been merged that are still in the list of current branches cluttering the workspace.

### Describe the solution you would like.

Select the box in the Settings that allows for "Automatically delete head branches". See [here for the instructions](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches) that could be followed by someone that has admin privileges. 

### Describe alternatives you have considered

Leave it as is where the person that merges in the pull request sees a message that the feature branch can be deleted.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by k-doering-NOAA** [comment]
One of the repos I work on uses the automatically delete branches option and I do like it! There is an option to "restore" branches if they get deleted but you want to keep them around. I'm not sure how long this restore option is available.
