### ISSUE TITLE
[Feature]: Update selectivity and recruitment interfaces

### ISSUE THREAD

**Issue by Bai-Li-NOAA** [NOAA-FIMS/FIMS#232]
### Is your feature request related to a problem? Please describe.

- [x] Evaluation method can be added to the logistic selectivity interface and then we can test the evaluation method in R.
- [x] The selectivity interface only has logistic selectivity, and a double logistic selectivity interface can be added.
- [x] Recruitment deviations and bias adjustment settings from [recruitment_base.hpp](https://github.com/NOAA-FIMS/FIMS/blob/main/inst/include/population_dynamics/recruitment/functors/recruitment_base.hpp) can be added to the recruitment interface. 

### Describe the solution you would like.

Update [rcpp_selectivity.hpp and rcpp_recruitment.hpp](https://github.com/NOAA-FIMS/FIMS/tree/main/inst/include/interface/rcpp/rcpp_objects) and add R tests following the [ewaa example](https://github.com/NOAA-FIMS/FIMS/blob/main/tests/testthat/test-ewaa.r) and the [tmb distributions example](https://github.com/NOAA-FIMS/FIMS/blob/main/tests/testthat/test-tmb-distributions.R).

Note: [basic R tests](https://github.com/NOAA-FIMS/FIMS/tree/test-add-more-tests/tests/testthat) for selectivity and recruitment interfaces have been added to the test-add-more-tests branch and I can submit a pull request this week.

### Describe alternatives you have considered

NA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ChristineStawitz-NOAA** [comment]
@Bai-Li-NOAA I'm running into an issue where the R cmd check runs forever - it seems to be getting stuck on running `testthat`. I thought maybe it was this [issue](https://stackoverflow.com/questions/41846465/testthat-fails-within-devtoolscheck-but-works-in-devtoolstest) so I tried unsetting the `R_TESTS` environment variable but that didn't seem to work. Have you seen this before?

**Comment by ChristineStawitz-NOAA** [comment]
I figured it out thanks to Github commit history! Something about the selectivity evaluate method is the problem.
