### ISSUE TITLE
Resolve merge conflicts between main and population

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS#259]

**Comment by ChristineStawitz-NOAA** [comment]
As part of this work we should look at these edits: 

- [ ] Move log_Fmort, log_q, Fmort and q class members from population.hpp to fleet.hpp
- [ ]  Move resize functions of log_Fmort, log_q, Fmort and q in [Initialize()](https://github.com/NOAA-FIMS/FIMS/blob/84f0cd2690a202ec885e2425739eb59b31d0b31d/inst/include/population_dynamics/population/population.hpp#L120) from population.hpp to fleet.hpp
- [ ]  Move [transformation functions](https://github.com/NOAA-FIMS/FIMS/blob/84f0cd2690a202ec885e2425739eb59b31d0b31d/inst/include/population_dynamics/population/population.hpp#L169) from population.hpp to fleet.hpp
- [ ]  Call Fmort and q in member functions using fleets[fleet_] ->

**Comment by ChristineStawitz-NOAA** [comment]
I did the above but broke something in Population related to fleet indexing

**Comment by k-doering-NOAA** [comment]
I know Christine is out this week, maybe someone who was involved in this (@EJDick-NOAA and @KyleShertzer-NOAA) could post on this issue if the fleet indexing needs to be fixed on the population branch? The tests are passing except for the documentation one, so I'm not sure how we knew fleet indexing isn't working?

**Comment by ChristineStawitz-NOAA** [comment]
@Andrea-Havron-NOAA updated the fleet indexing and we are currently testing the changes again

**Comment by Bai-Li-NOAA** [comment]
@ChristineStawitz-NOAA and @Andrea-Havron-NOAA, when merging main to the population branch, the code that resizes expected_catch, expected_index, and catch_numbers_at_age has been deleted. This change leads to [a failed test of CalculateCatchNumbersAA() and CalculateCatchWeigthAA()](https://github.com/NOAA-FIMS/FIMS/actions/runs/3633399426/jobs/6130369369#step:6:75). The test will run successfully if we add [the code below back to the fleet.hpp](https://github.com/NOAA-FIMS/FIMS/blob/unit-test-180-feat-population/inst/include/population_dynamics/fleet/fleet.hpp#L97-L99).

```c++
      expected_catch.resize(nyears);
      expected_index.resize(nyears); // assume index is for all ages.
      catch_numbers_at_age.resize(nyears * nages);
```

I can update the fleet.hpp and merge the changes to the population branch if it makes sense. Let me know if catch_numbers_at_age from fleet has been resized somewhere else.
