### ISSUE TITLE
[Refactor]: rename dimension folded indices to be clearer

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS#272]
### Refactor request

Right now we have `index_ay` (dimension-folded index at age a and year y) and `index_ay2` (dimension-folded index at age a-1 and year-1) and then `index_ay2+1` (dimension-folded index at age a-1 and year y) for the plus group calculation. It's not really intuitive what the indices are and it's kind of confusing the index named 2 happens before the original. At some point we can rename them so it doesn't confuse people.

### Expected behavior

It makes more sense to be to shorten index and lengthen the descriptors, for example:

`i_age_year` dimension-folded age and year 
`i_year_fleet` dimension-folded year and fleet
`i_lastage_lastyear`  dimension-folded previous year and previous age
`i_age_lastyear` dimension-folded previous age and current year (for plus group)

but I am open to feedback

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nathanvaughan-NOAA** [comment]
Those sound good to me, much better than the current names!

**Comment by Cole-Monnahan-NOAA** [comment]
Agreed that's an improvement. So when we have more model complexity we will just tack them on like

`i_age_year_sex_fleet_area_length` for e.g. CAAL data for a spatial, sex-specific model?

**Comment by Andrea-Havron-NOAA** [comment]
@Rick-Methot-NOAA, yes I think order should follow the nesting of loop. The original example was taken from a for loop in  population.hpp that started with [ages first](https://github.com/NOAA-FIMS/FIMS/blob/a96a987bf0aa8237cba0405128b8b1de97e4e9c2/inst/include/population_dynamics/population/population.hpp#L175). The main population loop starts with years first than ages. 

As part of this issue, should we make sure all the for loops follow the same order unless a different order is needed?

**Comment by Rick-Methot-NOAA** [comment]
That seems a good principle.
There will be some future features that depend on order of calculation.  For example, if there is movement between areas in each time step, then each area cannot be processed as a separate thread.  Also, if some parameter is to be density-dependent, then the value of that parameter in a given time step can only depend upon processes that have already affected the population up to that point in time.
