### ISSUE TITLE
[FEATURE] write dimension folding code for FIMS population

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS#28]
**Is your feature request related to a problem? Please describe.**
We need the user to see a population structured how they are familiar (e.g. matrix) while using a dimension-folded vector within C++ for efficiency

**Describe the solution you'd like**
An `R` interface should translate a matrix of age x years into a dimension folded vector that is looped through on the `C++` side to apply functions to the population segment.

- [ ] R interface
- [ ] C++ code header file(s) within population_dynamics/population folder (not sure if you want 1 or >1)
- [ ] test cases
- [ ] documentation 

**Describe alternatives you've considered**
A matrix structure to loop through the population will not scale well to the scenario where we have many population sub segments (e.g. sex, location, area).

**Describe a reference describing the statistical validity of this approach**
<please add any you can find>

**Describe if this is needed for a management application**
This is needed for efficency, not for management purposes.

**Additional context**

**Comment by timjmiller** [comment]
For an example of how (not?) to do this in TMB, see the "obsvec" in wham [here](https://github.com/timjmiller/wham/blob/38850fcb79c51f002531294b2fc08145032e6f27/src/wham_v0.cpp#L91) which is derived as a column of a data.frame ("obs") on the R side with pointers ("keep_*) for the various data sources [in this function](https://github.com/timjmiller/wham/blob/devel/R/set_osa_obs.R). This is necessary to use the one-step-ahead residual features of TMB.

**Comment by k-doering-NOAA** [comment]
Being worked on in https://github.com/NOAA-FIMS/FIMS/tree/feat-dimension-folding
