### ISSUE TITLE
[Refactor]: Inconsistent doxygen documentation for class members

### ISSUE THREAD

**Issue by Andrea-Havron-NOAA** [NOAA-FIMS/FIMS#282]
### Refactor request

Class member documentation in FIMS uses two styles:
`/*!<>*/` 
`/**<>*/`

### Expected behavior

Pick one style and make consistent throughout.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ChristineStawitz-NOAA** [comment]
We will be consistent using
`int var; /**< Detailed description after the member */`

**Comment by k-doering-NOAA** [comment]
@Bai-Li-NOAA , I know you mentioned being willing to help out with this - would you mind being the reviewer for it, once I submit the PR?

**Comment by Bai-Li-NOAA** [comment]
@k-doering-NOAA Sure thing. I can review the PR!

**Comment by k-doering-NOAA** [comment]
There are a [number of styles](https://www.doxygen.nl/manual/docblocks.html#cppblock), but I didn't see a preference specified in the google c++ style guide. I'll go with `/**` rather than `/*!` since it is the first option listed.
