### ISSUE TITLE
Get estimation working in TMB

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS#289]

**Comment by ChristineStawitz-NOAA** [comment]
Add lingering issues to Google doc: https://docs.google.com/document/d/1yCoHIrzRnM9UuK3IhGx9FGMsinP_tiesywF9cBdA9zs/edit

**Comment by Andrea-Havron-NOAA** [comment]
Development Tasks:

- [ ] Model.hpp
  - [ ] Minimalist code to be able to call MakeADFun and get output from population
    - [ ] information -> CreateModel
    - [ ] Dummy objective function that returns 0
  - [ ] Fully developed objective function

- [ ] FIMS.cpp
  - [ ] Set up similar to [Matthew’s modular example](https://github.com/NOAA-FIMS/ModularTMBExample/blob/20efe7fdc328da41dcc6edd998f9d1217d5058fb/src/tmb_objective_function.cpp#L233) (prepare_template analogous to add_to_tmb_fims)

- [ ] Interface.hpp
  - [ ] Add REPORT_F
  - [ ] Add ADREPORT_F
  - [ ] Add SIMULATE_F
  - [ ] Add IndicatorVector for model validation (could move to M2)

- [ ] rcpp_interface_base.hpp
  - [ ] Write get_parameter_vector function
  - [ ] Write get_random_effect_vector function following recommendations from vB demo subgroup

**Comment by Andrea-Havron-NOAA** [comment]
Developing tests on estimation in [integration-test-R](https://github.com/NOAA-FIMS/FIMS/tree/integration-test-R)
