### ISSUE TITLE
Design FIMS outputs and R processing/plotting functions

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS#292]
As discussed on 1-13 once `TMB` estimation is set up, we will need to implement a way to work with inputs and outputs in R and JSON. This group is tasked with specifying how these inputs and outputs should be structured and what they should contain. We started this in the FIMS workshop in 2022: https://docs.google.com/document/d/1YCz3HPef6MltF23qRhX9npUSQEHy3zzs4lEXnl5gKqw/edit#heading=h.mydsxb4q16zs

**Comment by JaneSullivan-NOAA** [comment]
@KyleShertzer-NOAA First step in the MCP is to install the model software. For BAM I see a reference to a "BAM-Sim1.tpl". Is this the same tpl as what's in the appendix of https://repository.library.noaa.gov/view/noaa/4847?

**Comment by KyleShertzer-NOAA** [comment]
No, it's different. BAM-Sim is an updated version and was also simplified for the model comparison project. I'll follow up with you by email to make sure you have what you need.

**Comment by JaneSullivan-NOAA** [comment]
Awesome! Well I think the plan is just to compare the deterministic OM (FIMS-C0) with FIMS (not any of the other EMs).... and then once FIMS is estimating we will run FIMS with the existing case studies in Li et al 2021. The benefit of that approach is that we don't actually need to be able to replicate any other of the other EMs.

For @k-doering-NOAA and @iantaylor-NOAA's group working with the github actions:  the Rdata file for FIMS-C0 is [here ](https://github.com/JaneSullivan-NOAA/Age_Structured_Stock_Assessment_Model_Comparison/blob/spatial-structure/example/FIMS-C0/output/OM/OM1.RData)

This file can be reproduced using this [example-FIMS-C0.R](https://github.com/JaneSullivan-NOAA/Age_Structured_Stock_Assessment_Model_Comparison/blob/spatial-structure/example/example-FIMS-C0.R)

**Comment by k-doering-NOAA** [comment]
@JaneSullivan-NOAA I just took a look this morning and it looks like the R data objects have a few additional elements and some different names on the spatial-structure branch compared to the main...is there a reason to use this branch over the main branch?

**Comment by JaneSullivan-NOAA** [comment]
@k-doering-NOAA it was the branch used in Age_Structured_Stock_Assessment_Model_Comparison/example/, was the one with most recent substantive developments, and I thought some of the spatial components might be useful in the future.
BUT i'm not surprised to hear things are different (they will be on the master branch too i believe), and that's no bueno for our future purposes unless we feel motivated to rerun all the other EMs. it looks like you started on this 2 hr ago.... can you hold off a bit while i get you an Rdata object from the Model_Comparison_Paper repo instead of the Age_Structured_Stock_Assessment_Model_Comparison repo?

**Comment by Andrea-Havron-NOAA** [comment]
I'll be meeting up with the group to add the REPORT_F TMB function to FIMS. We can then use this function to report out quantities through TMB output. 
I've implemented this already in my ar1xar1 TMB modular [example](https://andrea-havron-noaa.github.io/FIMS-software/docs/ar1xar1.html). 

- [ ] Add the [REPORT_F function](https://github.com/Andrea-Havron-NOAA/FIMS-software/blob/bc1cbbf08c2a73a4ebf2194b66d13559ca991719/ModularTMBExamples/ar1xar1/Common.hpp#L17) to inst/include/interface.hpp
- [ ] Add pointer to TMB objective function ([example](https://github.com/Andrea-Havron-NOAA/FIMS-software/blob/bc1cbbf08c2a73a4ebf2194b66d13559ca991719/ModularTMBExamples/ar1xar1/model.hpp#L29))
- [ ] Add REPORT_F within code base to report out variables of interest ([example](https://github.com/Andrea-Havron-NOAA/FIMS-software/blob/bc1cbbf08c2a73a4ebf2194b66d13559ca991719/ModularTMBExamples/ar1xar1/model.hpp#L65]))
