### ISSUE TITLE
[FEATURE] Create skeleton of objective function and R package

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS#3]
**Is your feature request related to a problem? Please describe.**
We need a starting point for FIMS that can compile and install effectively as an R package.

**Describe the solution you'd like**
A collection of folders following R package conventions that compiles and installs for users.

**Describe alternatives you've considered**
We have considered a standalone C++ or TMB model 

**Describe a reference describing the statistical validity of this approach**
n/a

**Describe if this is needed for a management application**
All RFMOs need the ability to quickly and efficiently run stock assessments that are reproducible. R packages are a way to accomplish this.

**Comment by Andrea-Havron-NOAA** [comment]
I've linked a couple useful resources with respect to R package development best practices:

- [CRAN Repository Policy](https://cran.r-project.org/web/packages/policies.html)
- [R packages book](https://r-pkgs.org/index.html), Whickham & Bryan, of particular importance is the [section](https://r-pkgs.org/src.html#cpp) on integrating C++ code

**Comment by Andrea-Havron-NOAA** [comment]
@msupernaw has set up a file structure for the inst/include folder in the [software_arch](https://github.com/NOAA-FIMS/software_arch/tree/main/fims/include) repository. How much of this do we want to port over for the initial skeleton?

**Comment by k-doering-NOAA** [comment]
The [usethis](https://usethis.r-lib.org/) package functions are a great way to get package skeletons. E.g., to set up the files you need for testing with testthat, you can use `usethis::use_testthat()`.  If you want to set up a skeleton of an R package, use `usethis::create_package()` (not needed for this repo, but makes life easier if we want to set up other repos in the future). I've also been finding `usethis::use_github_file()` and `usethis::use_github_action()` to be helpful in writing new usethis style functions (e.g., the [R functions in ghactions4r](https://github.com/nmfs-fish-tools/ghactions4r/blob/main/R/use_r_workflows.R)).

Note that I use Rstudio with R projects, and I'm not 100% sure how well usethis works if you are not using R projects...

**Comment by Andrea-Havron-NOAA** [comment]
Tips on setting up an R package based on TMB from the [TMB wiki](https://github.com/kaskr/adcomp/wiki/Development#distributing-code)

**Comment by Bai-Li-NOAA** [comment]
@k-doering-NOAA and I can work on 

- [ ] setting up the testing system (e.g., include the files and folders needed) on the FIMS repository
- [ ] getting the testing system running on GitHub actions
- [ ] adding [C++ files](https://github.com/Bai-Li-NOAA/TestingExamples/blob/main/.gitignore) to the current .gitignore file

**Comment by Andrea-Havron-NOAA** [comment]
Use the [feature branch](https://github.com/NOAA-FIMS/FIMS/tree/feat-issue-3-R-package-skeleton) when working on this issue
