### ISSUE TITLE
[Refactor]: Remove large files from FIMS repo

### ISSUE THREAD

**Issue by k-doering-NOAA** [NOAA-FIMS/FIMS#312]
### Refactor request

We have large files in the integration-test branch that we want to remove from history. However, we finally realized we cannot cleanly rewrite the history to remove them without affecting the main branch. So, we decided to go ahead and merge in the integration branch without removing the files and clean up later when there is less active work going on (i.e., no feature branches).

- [ ] @kellijohnson-NOAA and @k-doering-NOAA will experiment to come up with the command we need to use the [git filter-repo tool](https://github.com/newren/git-filter-repo) on FIMS appropriately.
- [ ] At an appropriate time, @kellijohnson-NOAA and @k-doering-NOAA will work with @ChristineStawitz-NOAA to remove the files from our history. However, this will be an entire re-write of the FIMS history, so we need to chose a time when there is no active work. Everyone will also need to reclone at that time.

### Expected behavior

No more large files in the commit history

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Andrea-Havron-NOAA** [comment]
Given that we are close to merging in PR#363, I want to revisit the timing for working on this issue

**Comment by kellijohnson-NOAA** [comment]
EVERYONE will have to reclone after we remove these files. So, ideally when there is only one branch without any local uncommitted changes.

**Comment by k-doering-NOAA** [comment]
I think for 307-data-validate we can cherry pick the 2 commits into a new branch, and it shouldn't be an issue (1b282393a0eb809b92d15f1f39f04c4a7a8fea45 and 1b282393a0eb809b92d15f1f39f04c4a7a8fea45) ? I think we could do the same for the add_to_fims_refactor (I don't think the delete debug.txt commit would need to be kept, just 4ed103c and c0ab357

**Comment by k-doering-NOAA** [comment]
Also adding that @ChristineStawitz-NOAA mentioned we should make sure to have a backup of the repo (or preferably multiple) when we do this. We are rewriting history, which is dangerous, so we want to back up in case the worst happens.

**Comment by k-doering-NOAA** [comment]
Ok. this is probably something we want to do before an official release as it will rewrite a LOT of history.

**Comment by ChristineStawitz-NOAA** [comment]
While doing this, we might want to delete the rapidjson header files that are not being used anymore - it's 28 files but they are small

**Comment by ChristineStawitz-NOAA** [comment]
We also have tmp.def in the history which is the largest file in there right now, just over 1.1 MB. Since all of these are small and it clones quickly, we (me, @kellijohnson-NOAA , @k-doering-NOAA ) don't think it's worth changing all the git references to delete from the history in the moment.
