### ISSUE TITLE
[Bug]: remove test data from FIMS-deterministic folder

### ISSUE THREAD

**Issue by Bai-Li-NOAA** [NOAA-FIMS/FIMS#317]
### Describe the bug

Ideally, we do not need to upload test data to FIMS remote repo because GHA workflow has [R code ](https://github.com/NOAA-FIMS/FIMS/blob/integration-test/.github/workflows/run-googletest.yml#L26-L31)to prepare test data. However, the GHA workflow failed to run and the log can be found [here](https://github.com/NOAA-FIMS/FIMS/actions/runs/4409696834/jobs/7726303397).

### To Reproduce

see GHA log [here](the GHA workflow failed to run and the log can be found [here](https://github.com/NOAA-FIMS/FIMS/actions/runs/4409696834/jobs/7726303397).)

### Expected behavior

The GHA runs successfully without FIMS-deterministic folder in the remote repo. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ChristineStawitz-NOAA** [comment]
Sorry we didn't get to this yesterday, I don't really understand if we need to fix this in M1 or if it can wait. What do you think @Bai-Li-NOAA ?

**Comment by Bai-Li-NOAA** [comment]
@ChristineStawitz-NOAA, I think we can wait and remove files during MQ.

**Comment by k-doering-NOAA** [comment]
What needs to happen is:
- [ ] remove the [`tests/integration/inputs/FIMS-deterministic`](https://github.com/NOAA-FIMS/FIMS/tree/main/tests/integration/inputs/FIMS-deterministic) folder
- [ ] Fix the [`setup_gtest()`](https://github.com/NOAA-FIMS/FIMS/blob/009f7636ae2c6fd1b2abfe48d85f9b1dd3b03cc1/R/setup_gtest.R#L9) function
