### ISSUE TITLE
[Bug]: build-deploy-doxygen GHA workflow does not work

### ISSUE THREAD

**Issue by Bai-Li-NOAA** [NOAA-FIMS/FIMS#320]
### Describe the bug

The build-deploy-doxygen GHA workflow does not work. It returns following error when pushing git commits to FIMS-docs repo.

```
+ git push -u origin HEAD:main
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/NOAA-FIMS/FIMS-docs.git/'
```

### To Reproduce

See GHA log [here](https://github.com/NOAA-FIMS/FIMS/actions/runs/4440755965/jobs/7853849480)

### Expected behavior

build-deploy-doxygen GHA workflow runs fine and doxygen files can be pushed to FIMS-docs repo.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by k-doering-NOAA** [comment]
Hmm, I wonder if there was a token and it expired? Looks like Christine may have generated it?

I've also generally had a issues with that copy-file-to-another-repo action

**Comment by ChristineStawitz-NOAA** [comment]
@k-doering-NOAA the token expired back in November, and I think I generated a new token then, so I'm not sure why this would have started happening just now. I can generate a new token if needed!

**Comment by k-doering-NOAA** [comment]
@ChristineStawitz-NOAA I put a note for us to discuss this in our upcoming meeting

**Comment by k-doering-NOAA** [comment]
Christine re-generated the token and added the new one to the secret - we are back up and running!
