### ISSUE TITLE
[Bug]: evaluate method from maturity and selectivity Rcpp interfaces does not work

### ISSUE THREAD

**Issue by Bai-Li-NOAA** [NOAA-FIMS/FIMS#321]
### Describe the bug

The R CMD Check from the population-Rcpp-interface branch did not pass because the evaluate methods (e.g., `maturity$evaluate(10.0)`) from maturity and selectivity modules did not work in R. The two modules use logistic function in the evaluate() and the logistic function uses exp() from TMB. The R code stop working while running exp() from [here](https://github.com/NOAA-FIMS/FIMS/blob/e1abaa265bd3d8fd8a7f8599460443b7c25e160d/inst/include/common/fims_math.hpp#L93). Need to figure out how to use [TMB exp()](https://github.com/kaskr/adcomp/blob/master/TMB/inst/include/cppad/local/exp_op.hpp) in FIMS. 

### To Reproduce

I created a branch `bug-selectivity-Rcpp` and added [`Rcout` code](https://github.com/NOAA-FIMS/FIMS/blob/66fd4367c73dbe0b8af3472b2efc8b5de70169b2/inst/include/common/fims_math.hpp#L93-L96) to print output for debugging. To reproduce the error, go to `bug-selectivity-Rcpp` branch, use `devtools::load_all()` to compile the code in R. Then run the following code in R.

```r
 fims <- Rcpp::Module("fims", PACKAGE = "FIMS")

  # Create selectivity1
  selectivity1 <- new(fims$LogisticSelectivity)

  selectivity1$median$value <- 10.0
  selectivity1$median$min <- 8.0
  selectivity1$median$max <- 12.0
  selectivity1$median$is_random_effect <- TRUE
  selectivity1$median$estimated <- TRUE
  selectivity1$slope$value <- 0.2

 selectivity1$evaluate(10.0)
```

Output in R:
```r
median =10
x =10
slope =0.2
exp(-1.0 * slope * (x - median))......
```

### Expected behavior

The evaluate() from maturity and selectivity module work fine and R tests pass.

### Which OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ChristineStawitz-NOAA** [comment]
In babySAM, the logistic function is written in log space to keep it numerically stable, we may need to do this here.

```R -d gdb
run -f script.R
```

should run this

**Comment by Bai-Li-NOAA** [comment]
Thanks @msupernaw for solving the issue. The following code has been added to [fims_math.hpp](https://github.com/NOAA-FIMS/FIMS/blob/03df96a220a73b0b44215e7cf625c8398a814149/inst/include/common/fims_math.hpp#L50-L89) in order to make both exp() and log() work. evaluate() from maturity and selectivity modules uses double as input. std::exp() will be used when the input value is double, instead of using exp() from TMB cppAD. 
```r
template <>
inline const double exp(const double &x) {
  return std::exp(x);
}

template <>
inline const double log(const double &x) {
  return std::log(x);
}
```

**Comment by Bai-Li-NOAA** [comment]
> In babySAM, the logistic function is written in log space to keep it numerically stable, we may need to do this here.
> 
> ```
> R -d gdb
> run -f script.R
> ```
> 
> should run this

@ChristineStawitz-NOAA and @Andrea-Havron-NOAA , the exp() and log() issue here is caused by the input type in the evaluate() method. Should we open a separate issue to check all the exp() in FIMS and update them in log space if they are not numerically stable?

**Comment by Andrea-Havron-NOAA** [comment]
> > In babySAM, the logistic function is written in log space to keep it numerically stable, we may need to do this here.
> > ```
> > R -d gdb
> > run -f script.R
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > should run this
> 
> @ChristineStawitz-NOAA and @Andrea-Havron-NOAA , the exp() and log() issue here is caused by the input type in the evaluate() method. Should we open a separate issue to check all the exp() in FIMS and update them in log space if they are not numerically stable?

I can file a separate issue for this
