### ISSUE TITLE
[Refactor]: fims math needs "::" in front of exp and log  in the TMB_MODEL compilation

### ISSUE THREAD

**Issue by msupernaw** [NOAA-FIMS/FIMS#322]
### Refactor request

fims math needs "::" in front of exp and log in the TMB_MODEL compilation to ensure the compiler searches for the global versions of these functions defined for TMB types. Otherwise, there's a recursive call to the versions defined in the fims namespace.

### Expected behavior

The proper versions will be called for TMB types.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ChristineStawitz-NOAA** [comment]
I tried this out on the linked branch but it doesn't compile

**Comment by msupernaw** [comment]
The problem was that the compiler could find a version of the functions for double types. The solution was to add the following below the templated functions:

template <>
inline const double exp(const double &x) {
  return std::exp(x);
}

template <>
inline const double log(const double &x) {
  return std::log(x);
}
