### ISSUE TITLE
[Feature]: add ability for different fleet NLL distributions

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS#334]
### Is your feature request related to a problem? Please describe.

Right now the fleet index NLL is hardcoded as a lognormal and the age comp NLL is hardcoded as a multinomial.

### Describe the solution you would like.

There should be flexibility in the option for NLLs

### Describe alternatives you have considered

Dirichlet-Multinomial for age comps
Normal for indices

**Comment by ChristineStawitz-NOAA** [comment]
The ideal solution would likely use inheritance to separate discrete and continuous distributions so we can use shared properties for all the possible age composition types e.g. multinomial vs dirichlet and index e.g. normal, lognormal

**Comment by Andrea-Havron-NOAA** [comment]
Revisit whether or not the likelihood functions can be converted from C++ classes to functions so they are referenced in a style more familiar with FIMS developers.

**Comment by Andrea-Havron-NOAA** [comment]
SetAgeCompLikelihoods and SetIndexLikelihoods can be accessed by the user to set distribution ids

**Comment by Andrea-Havron-NOAA** [comment]
rcpp_nll.hpp can be used to set likelihoods through the interface

**Comment by ChristineStawitz-NOAA** [comment]
I think we can knock this out when we fix this issue, but I noticed right now we get errors in `FIMS_LOG` that the likelihood functions are not defined even when everything runs correctly: `Error: Expected age comp likelihood function not defined for fleet 1, likelihood function 1`

**Comment by nathanvaughan-NOAA** [comment]
Yep, that error was fixed in the updated logging code that got missed in the hard rebase. It will be fixed once I fix the new merge conflicts and make a pull request for the fixed log code that I have been too slow to finish.

**Comment by Andrea-Havron-NOAA** [comment]
close with PR #646
