### ISSUE TITLE
[FEATURE] `Rcpp` interface for logistic selectivity module and beverton holt recruitment

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS#34]
**Is your feature request related to a problem? Please describe.**
We need to expose the logistic selectivity function added in pull request #31 to `R` users following the steps provided in the `Rcpp` training.

**Describe the solution you'd like**
Use of the `Rcpp` export functionality to create a module for selectivity that can be accessed in `R`

**Describe alternatives you've considered**
The alternative would be using the base `R` functionality to exporting modules, which is harder to use than the macros provided by `Rcpp`

**Describe a reference describing the statistical validity of this approach**
n/a

**Describe if this is needed for a management application**
n/a

**Comment by Bai-Li-NOAA** [comment]
I just noticed that the R cmd check failed after adding RCPP_MODULE in the interface.hpp (GitHub actions log can be found [here}(https://github.com/NOAA-FIMS/FIMS/runs/5650227143?check_suite_focus=true)). I tried to fix the issue but failed. Below are other issues that may be not related to the RCPP_Module code, but need to be fixed before developing Rcpp module?

The error message I got when compiling selectivity module:
`Desktop/fims_workshop/FIMS/inst/include/common/model_object.hpp:42:19: error: 'FIMSTraits' in namespace 'fims' does not name a template type
     typedef fims::FIMSTraits<T>::VariableT variable_t;
                   ^~~~~~~~~~
`
Maybe we need to modify interface.hpp and include FIMSTraits in namespace fims{}?
