### ISSUE TITLE
check integration-test-R branch

### ISSUE THREAD

**Issue by Andrea-Havron-NOAA** [NOAA-FIMS/FIMS#365]
We originally merged intergration-test-estimation-R into intergration-test-R branch but then continued working in integration-test-estimation-R. There may be changes in integration-test-R branch that we need to cherry pick before completing the PR#363

See the [FIMS network](https://github.com/NOAA-FIMS/FIMS/network):
![image](https://github.com/NOAA-FIMS/FIMS/assets/85530309/2784cbeb-922e-478a-824f-b1a0554fca19)

**Comment by Andrea-Havron-NOAA** [comment]
Thanks @Bai-Li-NOAA, I used [github compare](https://github.com/NOAA-FIMS/FIMS/compare/integration-test-R...integration-test-estimation-R-clear-FIMS). 

There are a couple of differences worth noting between the two branches:

- There is a bug in integration-test-estimation-R-clear-FIMS - fleet.hpp where the dimensions of the age comp likelihood is [hard coded to 360](https://github.com/NOAA-FIMS/FIMS/blob/10d5103cecdf2e37b724eb15dbf66dfb146c472b/inst/include/population_dynamics/fleet/fleet.hpp#L159) (to match the model comparison project). We might need to switch back to how this section was written in [integration-test-R](https://github.com/NOAA-FIMS/FIMS/blob/88942e9da522d56aaa4eb86dcd9483d76b3a4806/inst/include/population_dynamics/fleet/fleet.hpp#L149). A comment has been added to PR#363 to track this issue.
- integration-test-R has a [FIMS_Rcpp_test.R](https://github.com/NOAA-FIMS/FIMS/blob/integration-test-R/tests/testthat/FIMS_Rcpp_test.R) that doesn't exist in integration-test-estimation-R-clear-FIMS. Do we want to port it over? We may need to rename it test-fims-rcpp.R

**Comment by Bai-Li-NOAA** [comment]
> * integration-test-R has a [FIMS_Rcpp_test.R](https://github.com/NOAA-FIMS/FIMS/blob/integration-test-R/tests/testthat/FIMS_Rcpp_test.R) that doesn't exist in integration-test-estimation-R-clear-FIMS. Do we want to port it over? We may need to rename it test-fims-rcpp.R

Agree, I have renamed it to test-fims-rcpp.R in integration-test-estimation-R-clear-FIMS last month and it can be found [here](https://github.com/NOAA-FIMS/FIMS/blob/integration-test-estimation-R-clear-FIMS/tests/testthat/test-fims-rcpp.R).

**Comment by Andrea-Havron-NOAA** [comment]
Thanks @Bai-Li-NOAA, I missed that! Since I commented on the PR about the first issue in fleet, we can probably close out this issue and delete the integration-test-R branch.
