### ISSUE TITLE
Review stale branches

### ISSUE THREAD

**Issue by Andrea-Havron-NOAA** [NOAA-FIMS/FIMS#366]
There are a number of [stale branches](https://github.com/NOAA-FIMS/FIMS/branches/stale) in FIMS. We should review them and decide which ones can be deleted.

**Comment by k-doering-NOAA** [comment]
There is also an "automatic deletion of merged branches" option, which I'm not sure if we have on or not for FIMS? It might help keep the number of stale branches down in the future.

**Comment by ChristineStawitz-NOAA** [comment]
I forked the project so FIMS-atl can continue to exist in its own repo on the fims_atl branch: https://github.com/NOAA-FIMS/FIMS-ATL

I deleted all the other stale branches.

There are two remaining branches open without pull requests, both related to issue #307 for which work is ongoing but got moved to MQ. I guess we probably want to leave those open until we can rebase main onto them? Open to other suggestions!

**Comment by kellijohnson-NOAA** [comment]
307-run has been deleted and we plan on rebasing 307-data-validate.
