### ISSUE TITLE
add vignette for FIMS visualization

### ISSUE THREAD

**Issue by Andrea-Havron-NOAA** [NOAA-FIMS/FIMS#367]
A vignette is needed to help explain and visualize the FIMS architecture

**Comment by Andrea-Havron-NOAA** [comment]
@ChristineStawitz-NOAA, @Bai-Li-NOAA, @k-doering-NOAA, and @msupernaw 

Can you review the [vignette](https://github.com/NOAA-FIMS/FIMS/blob/vignette-fims-path/vignettes/fims-path-maturity.Rmd) I made detailing the maturity module? Some finer details about information may not be correct.

I think devtools::install() will build the .html file locally. You can also pull down the branch and knit the Rmarkdown file to view it locally, but it will not save. I created the vignettes folder by calling usethis::use_vignette(), which set up a .gitignore with html set to be ignored.

**Comment by Andrea-Havron-NOAA** [comment]
Here's a link to [R vignette](https://r-pkgs.org/vignettes.html#:~:text=First%2C%20it's%20important%20to%20realize,as%20devtools%3A%3Abuild()%20.) best practices. It sounds like the best way to publish the vignette online is via pkgdown

**Comment by Bai-Li-NOAA** [comment]
@Andrea-Havron-NOAA. Thanks for writing the vignette. This is great! Here are some minor suggestions. 

- I got this error: ```r Error: attempt to apply non-function``` when running the first two code chunks in R. Removing some `fims$` might fix the problem. For example,

```r
remotes::install_github("NOAA-FIMS/FIMS")
library(FIMS)
fims <- Rcpp::Module("fims", PACKAGE = "FIMS")
maturity <- new(fims$LogisticMaturity)
maturity$median$value <- 10
maturity$median$is_random_effect <- FALSE
maturity$median$estimated <- FALSE
maturity$slope$value <- 0.2
maturity$slope$is_random_effect <- FALSE
maturity$slope$estimated <- FALSE

population <- new(fims$Population)
#set up population specific parameters
#...
#set maturity for the population
population$SetMaturity(maturity$get_id())
```

- I was not able to run the three populations example and got this error message: ```r Error in p.maturity_id : object 'p.maturity_id' not found```. It might be related to how to access elements of nested lists.

- If you want to display C++ code with highlighted text (e.g., the section discusses how to link maturity pointers in population to equal the maturity pointer in information), you can change the language name in the chunk header from `r` to the engine name, e.g., 
````markdown
```{c, results='hide'}
code
```
````

**Comment by MOshima-PIFSC** [comment]
@Andrea-Havron-NOAA this looks really good. I really liked the inclusion of the diagrams. I just had a few comments:

- I was also getting first error @Bai-Li-NOAA mentioned but then ran the code she suggested (removing `fims$`) and now when I run `population$SetMaturity(maturity$get_id())` I get `Error in envRefInferField(x, what, getClass(class(x)), selfEnv) : 
  'SetMaturity' is not a valid field or method name for reference class "Rcpp_Population"`. 
- When I knit the rmd locally, it gave a warning to adjust the title in the yaml from `%\VignetteIndexEntry{FIMS path: maturity}` to `%\VignetteIndexEntry{FIMS path: Maturity}` to match the title in the top line. 
- The line "All modules from FIMS contain member fields corresponding to their parameters that inherit from the Parameter class" is a bit confusing for me as a non-C++ person.

**Comment by Andrea-Havron-NOAA** [comment]
Thanks @Bai-Li-NOAA and @MOshima-PIFSC for your feedback!

I've made the corrections to the R code and title that you all recommended. @MOshima-PIFSC, the SetMaturity function was added in the integration-test-estimation-R-clear-FIMS branch, so this line of code will throw an error until that PR is merged into main. You could also modify the rmarkdown to install from that particular branch:
`remotes::install_github("NOAA-FIMS/FIMS@integration-test-estimation-R-clear-FIMS")`

@MOshima-PIFSC, I'll work on re-wording the description about member fields so it is easier to understand. Thanks for the recommendation to clarify!

I have also added a lot more detail to the R code example at the end of the vignette.
