### ISSUE TITLE
[Feature]:  restrict codespace machine types to the ones that work

### ISSUE THREAD

**Issue by k-doering-NOAA** [NOAA-FIMS/FIMS#373]
### Is your feature request related to a problem? Please describe.

I keep forgetting to use a higher core machine for codespaces since the 2 core one won't work.

### Describe the solution you would like.

There is a way to set "codespace policies" so that only certain machine types are allowed: https://github.com/organizations/noaa-fims/settings/codespaces/policies/new . It might be helpful to restrict the machine types to only ones we know work.

### Describe alternatives you have considered

Documentation in an obvious place with a reminder of which machine types work

### Statistical validity, if applicable

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ChristineStawitz-NOAA** [comment]
Thanks for finding this @k-doering-NOAA ! I just restricted us to the 16GB machine type, only for FIMS and FIMS-ATL repo, so we can still use smaller machines on the other repos.

**Comment by k-doering-NOAA** [comment]
Perfect @ChristineStawitz-NOAA , thanks!
