### ISSUE TITLE
[Bug]: failing test on codespaces, saved files

### ISSUE THREAD

**Issue by k-doering-NOAA** [NOAA-FIMS/FIMS#376]
### Describe the bug

During our group's code review meeting, we were still getting a failing test on codespaces due to this line:
```r
expect_silent(save_png(plot(fims_frame)))
```

We also saw that there were some files created when running test that: a fleets.log file and a *.md file. We thought it would be better if these files weren't created so that the workspace remains unchanged when running the testthat tests.

### To Reproduce

Open codespaces and run `devtools::test()`

### Expected behavior

All tests passing and no files created

### Which OS are you seeing the problem on?

Linux

### Which version of FIMS are you seeing the problem on?

https://github.com/NOAA-FIMS/FIMS/tree/integration-test-estimation-R-clear-FIMS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bai-Li-NOAA** [comment]
Is the error message from the failed test similar to this one: https://github.com/NOAA-FIMS/FIMS/issues/360? @ChristineStawitz-NOAA has fixed the bug by adding libxtst6 and libxt6 to the codespace devcontainer. I wonder if opening a new codespace session from the main branch and then `git checkout` the working branch would resolve the issue.

**Comment by ChristineStawitz-NOAA** [comment]
The first step here is to determine if this still happens on main, we might be able to just close this. If it is still happening, fixing this is pretty high priority.
