### ISSUE TITLE
[Refactor]: Consistent use of bias correction or bias adjustment across FIMS

### ISSUE THREAD

**Issue by Andrea-Havron-NOAA** [NOAA-FIMS/FIMS#385]
### Refactor request

Bias adjustment and bias correction are used interchangeably throughout FIMS. 

### Expected behavior

Pick one and make it consistent across the codebase. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bai-Li-NOAA** [comment]
Following the discussion from #185. We plan to remove bias adjustment from FIMS and let TMB do it externally.
