### ISSUE TITLE
[Refactor]: Change dimension of parameters from scalar to vector

### ISSUE THREAD

**Issue by Andrea-Havron-NOAA** [NOAA-FIMS/FIMS#386]
### Refactor request

Update parameters from scalars to vectors to allow for time-varying processes, e.g., M and q.

### Expected behavior

- Example q: Instead of indexing by year, could index based on the length of the parameter. So if it’s constant, its index length = 1, If its a two time block model, its index length = 2, if it’s q with a random walk, it’s an index length = nyear

- “Biopars” from Anders - putting in these parameters as matrices instead of vectors to allow for correlation

**Comment by Andrea-Havron-NOAA** [comment]
Related to Issue #388

**Comment by iantaylor-NOAA** [comment]
The issue of making parameters time-varying has come up in separate places recently:
- the need for time-varying retention and mortality parameters was mentioned in the draft discard design doc: https://docs.google.com/document/d/1QBGyKVN5-YXKfJazbdALgbdE2jIYzzZqBtKEGLegt-U/edit?pli=1 (access limited to NOAA account)
- the potential need for time-varying sex ratio parameter was mentioned here: https://github.com/NOAA-FIMS/FIMS/issues/521#issuecomment-2256863346

Maybe this is already the plan, but can we just set up all parameters allow time-variation by default even if we don't yet have a way to turn on that variation?

**Comment by Andrea-Havron-NOAA** [comment]
@msupernaw, moving this issue to sprint 2 so it can be completed before the start of sprint 3

**Comment by Andrea-Havron-NOAA** [comment]
This issue also needs to consider:

- [ ] Dimension checking and throwing error in the Rcpp interface
- [ ] Handling both scalar and vector input

**Comment by Andrea-Havron-NOAA** [comment]
close with PR #669
