### ISSUE TITLE
[Feature]: Need ParameterVector class in Rcpp Interface

### ISSUE THREAD

**Issue by Andrea-Havron-NOAA** [NOAA-FIMS/FIMS#388]
### Is your feature request related to a problem? Please describe.

Currently the Rcpp interface only has a scalar Parameter class. This has led to inconsistencies and repetitive code to handle parameters that need to be vectors. 

Scalar parameters have fields: `value,` `is_random_effect` and `is_estimated` for setting values in R and indicating if the parameter is a random effect and if it is estimated. Vectorized parameters have a different interface. For example, the F parameter is set using a `log_Fmort` field instead of  `value`  and the booleans for random effects and estimation are: `random_F` and `estimate_F`. As the naming convention depends on the parameter name, duplicative code needs to be written for each vectorized parameter. 

### Describe the solution you would like.

ParameterVector class that can be used for all vectorized parameters. This class can standardize naming conventions when setting values and booleans in R.

Outstanding question: how to update naming conventions to better decribe values that are sometimes treated as data and sometimes treated as parameters? Should there be a distrinction? When using TMB, all values (data and parameters) are CppAD Type to track derivatives. Derivatives need to be tracked for data when running TMB validation, one-step-ahead residuals.

### Describe alternatives you have considered

Keep the current solution: only a scalar Parameter class and unique naming conventions when parameters are vectors

### Statistical validity, if applicable

Flexibility is needed to be able to turn on time variation for parameters, see Issue #386

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Andrea-Havron-NOAA** [comment]
Developing prototype using [ModularTMBExample](https://github.com/NOAA-FIMS/ModularTMBExample/tree/FIMS-v0100-nll-refactor-2) using [VariableVector](https://github.com/NOAA-FIMS/ModularTMBExample/blob/f29bd2a3cf4af863f8a3cccd69085d84ecd30ebc/inst/include/interface/rcpp/rcpp_objects/rcpp_interface_base.hpp#L55) class.

**Comment by msupernaw** [comment]
I've introduced a new class to the Rcpp interface called VariableVector in ModularTMBExample. In addition to holding Variable types, I've included common vector operations in the file operators.R. This refactor eliminates the need for top-level fields like "is_random_effect", "is_estimated", etc for vectors types in submodules. This also moves control to individual elements in the vector and makes TMB::Map easier to implement in the future (which has also been implemented in ModularTMBExample). VariableVector types have a default length of 1 for scalar representation when necessary.

**Comment by Andrea-Havron-NOAA** [comment]
Proposed M2 tasks:

- [ ] VariableVector class
- [ ] ?Add implicit conversion from scalar to vector of 1 
  - this will affect readability as code will read as though parameter is a scalar when it is being treated as a vector
- [ ] refactor all parameters in FIMS to be VariableVectors (issue #386) 
  - possible M2Q task

**Comment by Andrea-Havron-NOAA** [comment]
5/28 Hackathon tasks:
Proposed Branch: dev/add-vector-class

- [ ] Add VariableVector class to FIMS [rcpp_interface_base.hpp](https://github.com/NOAA-FIMS/FIMS/blob/main/inst/include/interface/rcpp/rcpp_objects/rcpp_interface_base.hpp) (copy from [ModularTMBExample](https://github.com/NOAA-FIMS/ModularTMBExample/blob/da27b8425873a8dfa26c1d9214e7d3776d34e59b/inst/include/interface/rcpp/rcpp_objects/rcpp_interface_base.hpp#L55))
  - [ ] Modify to work with FIMS
- [ ] Expose VariableVector class to R ([ex](https://github.com/NOAA-FIMS/ModularTMBExample/blob/da27b8425873a8dfa26c1d9214e7d3776d34e59b/inst/include/interface/rcpp/rcpp_interface.hpp#L104)) in [rcpp_interface.hpp](https://github.com/NOAA-FIMS/FIMS/blob/288a6ac8c40407d511770cde4d041bafd2bf69ec/inst/include/interface/rcpp/rcpp_interface.hpp#L320) 
- [ ] Copy R/Operator.R from ModularTMBExample to FIMS 
- [ ] Copy test-v.R from ModulatTMBExample to FIMS
  - [ ] Rename test-unit-rcpp-interface-variable-vector.R
  - [ ] Expand tests and add testthat commands
- [ ] Pass devtools::test
- [ ] Pass devtools::check

**Comment by Andrea-Havron-NOAA** [comment]
close with PR#604
