### ISSUE TITLE
github actions: investigate build triggers

### ISSUE THREAD

**Issue by k-doering-NOAA** [NOAA-FIMS/FIMS#39]
**Is your feature request related to a problem? Please describe.**
We may be generating github action runs more often than necessary. For example, if a github actions runs on every push, we probably do not also need it to run when a PR is opened, because the same code is being tested twice.

**Describe the solution you'd like**
Limit github action runs to only when they are necessary.

**Describe alternatives you've considered**
We could just leave the build triggers as is, but the extra runs are unnecessary and may also cause confusion.

**Describe a reference describing the statistical validity of this approach**
n/a

**Describe if this is needed for a management application**
n/a

**Additional context**
I'm happy to investigate this, unless @Bai-Li-NOAA would like to!

**Comment by ChristineStawitz-NOAA** [comment]
I think this is closed, but let's use the discussion on wednesday to reopen any needed issues on gh actions
