### ISSUE TITLE
[Discussion]: Ways to improve Rcpp Interface

### ISSUE THREAD

**Issue by Andrea-Havron-NOAA** [NOAA-FIMS/FIMS#390]
The Rcpp interface has been flagged as a section of FIMS that can be restructured to improve readability and reduce redundancy. Currently, every variable that gets passed from R into FIMS through the interface needs to be passed to four different pointers so that TMB can track the estimated value along with the first, second, and third derivatives.

Solutions: 
- @msupernaw is developing a templated function, `add_to_fims_tmb_internal()` to reduce repetition in code. See [this branch](https://github.com/NOAA-FIMS/FIMS/blob/add_to_fims_refactor/inst/include/interface/rcpp/rcpp_objects/rcpp_maturity.hpp). With this change, each variable would only need to be passed to a single pointer for information and a single pointer for the respective FIMS module ([maturity example](https://github.com/NOAA-FIMS/FIMS/blob/ddef525135112dea1953361a255b07a0772a61ec/inst/include/interface/rcpp/rcpp_objects/rcpp_maturity.hpp#L91)). This templated function then gets called with the four TMB types: TMB_FIMS_REAL_TYPE (estimate), TMB_FIMS_FIRST_ORDER (1st derivative), TMB_FIMS_SECOND_ORDER (2nd derivative), TMB_FIMS_THIRD_ORDER (3rd derivative).
- TMB versions > 1.8.0 allow users to rely on the new AD framework, TMBad instead of CppAD. The set-up for TMBad is more generic and would not require expicitly declaring four instances of each parameter. Switching FIMS over to TMBad would allow developers to reduce the complexity of the Rcpp interface
-  FIMS has a function, [`create_rcpp_interface_object.R`](https://github.com/NOAA-FIMS/FIMS/blob/main/R/create_rcpp_interface_object.R) to automate the generation of the Rcpp interface object files for developers. Once the Rcpp interface is refactored, the development of this script can be completed.

Please provide comments on the proposed solutions and/or add additional questions, comments or suggestions for improving the Rcpp interface.

**Comment by Andrea-Havron-NOAA** [comment]
related issue #384

**Comment by ChristineStawitz-NOAA** [comment]
If we use the templated function `add_to_fims_tmb_internal()`, would we later be able to switch to TMBad by only changing the code within that function? Or would we need to refactor again? I'm in favor of only having to refactor once if at all possible.

**Comment by ChristineStawitz-NOAA** [comment]
I think we fixed the first bullet point, and the other two are tracked in other issues, so closing for now
