### ISSUE TITLE
[BUG] call-workflow requires pkgbuild library

### ISSUE THREAD

**Issue by Andrea-Havron-NOAA** [NOAA-FIMS/FIMS#4]
**Describe the bug**
Error generated from call-workflow: 'pkgbuild' is required to compile packages with a 'src/'. See error message [here](https://github.com/NOAA-FIMS/FIMS/runs/5060549810?check_suite_focus=true)

**To Reproduce**
1. If the pkgbuild library is installed, uninstall using `uninstall.packages('pkgbuild')`
2. Replicate the call-workflow code the generates the error: `roxygen2::roxygenize()`

**Expected behavior**
![image](https://user-images.githubusercontent.com/85530309/152462438-6673cb3d-8ea0-4974-adde-50bb2f32d7f0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser: chrome

**Comment by k-doering-NOAA** [comment]
Thanks for reporting this, Andrea! This was fixed by https://github.com/nmfs-fish-tools/ghactions4r/commit/35d0d03712f5e109bc1d9514cf6beddf5192d360. I reran github actions and [it now passes](https://github.com/NOAA-FIMS/FIMS/actions/runs/1792583869)
