### ISSUE TITLE
Github action that automatically adds labels to incoming issues

### ISSUE THREAD

**Issue by k-doering-NOAA** [NOAA-FIMS/FIMS#40]
**Is your feature request related to a problem? Please describe.**
The triage and kind: bug or kind:feature issues are helpful, but are not added by default to incoming issues. Instead, they don't get used or they need to be manually added when adding an issue.

**Describe the solution you'd like**
We can use a [github action to add labels automatically](https://github.com/actions-ecosystem/action-add-labels) when issues are created to avoid this manual work.

**Describe alternatives you've considered**
Maybe it isn't necessary to add labels initially, as long as it is obvious they need to be manually triaged.

**Describe a reference describing the statistical validity of this approach**
n/a

**Describe if this is needed for a management application**
n/a

**Additional context**
This should be quick to set up given there is already an action we could use.

**Comment by ChristineStawitz-NOAA** [comment]
I think this is just a bug in the issue template - trying to fix on the patch branch

**Comment by k-doering-NOAA** [comment]
Very cool, I didn't realize you could add it right to the template! That makes life even easier.

For future reference (or those learning like me), there is an example of how to auto apply labels using templates here: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

**Comment by ChristineStawitz-NOAA** [comment]
I think this should be fixed now, let me knowif other labels need to be added!
