### ISSUE TITLE
Modify CalculateBiomass from population.hpp

### ISSUE THREAD

**Issue by Andrea-Havron-NOAA** [NOAA-FIMS/FIMS#401]
The current implementation of CalculateBiomass is:
 this->biomass[year] +=
        this->numbers_at_age[index_ya] * growth->evaluate(ages[age]);

From @timjmiller:
change the component of this product to something like this-> biomass_at_age[index_ya] which could be populated from "growth" since there are more aspects of growth than just the weight at age.

**Comment by Cole-Monnahan-NOAA** [comment]
Sorry I don't follow this issue could someone please clarify a bit what the question is?

**Comment by nathanvaughan-NOAA** [comment]
We populated the weight_at_age[] vector in the population.hpp Prepare() function using the growth evaluate function. We then replaced  growth->evaluate(ages[age]) with this->weight_at_age[age] throughout the population.hpp file.
