### ISSUE TITLE
[Refactor]: fims_math exp() and log() functions 

### ISSUE THREAD

**Issue by nathanvaughan-NOAA** [NOAA-FIMS/FIMS#404]
### Refactor request

We need more documentation and testing of the exp() and log() functions in fims_math to describe the difference and importance of the template<class T> using fims::exp() vs template<> using std::exp(). 

### Expected behavior

I expect we will all understand this once more documentation is added. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Andrea-Havron-NOAA** [comment]
Unit tests exist for fims::exp() and fims::log(), but these are only called when STD_LIB is defined. There are currently no unit tests on the exp() and log() functions when TMB is defined. Unit tests can be created using testthat.

**Comment by Andrea-Havron-NOAA** [comment]
broader issue: how much do we need to unit test TMB functions
