### ISSUE TITLE
[Refactor]: Change remotes from Suggests to Imports in DESCRIPTION

### ISSUE THREAD

**Issue by Andrea-Havron-NOAA** [NOAA-FIMS/FIMS#405]
### Refactor request

remotes is currently listed under Suggests, but remotes is used in data_mile1.R file.

### Expected behavior

move remotes to Imports so users can have access to this function.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Andrea-Havron-NOAA** [comment]
In the future, we will want to update remotes to pak. Currently the lifecycle badge for remotes is stable while the badge for pak is experimental.

https://github.com/r-lib/pak
https://github.com/r-lib/remotes

**Comment by kellijohnson-NOAA** [comment]
{remotes} is not used in the package by users though, it is only used in the script to make the data frame. I advocate for leaving it as a suggested package.

**Comment by k-doering-NOAA** [comment]
Thanks @kellijohnson-NOAA, I was trying to remember if the data-raw folder included code that the users have to run or not to get the dataframe (I was the one who suggested to Andrea remotes might need to be an Imports instead). - sounds like it is not something for users, so I agree with your point!
