### ISSUE TITLE
Add additional documentation and error statements to information.hpp

### ISSUE THREAD

**Issue by Andrea-Havron-NOAA** [NOAA-FIMS/FIMS#407]
From @nathanvaughan-NOAA:

For information.hpp there are a lot of places that need errors to be logged that currently just have //log error comments showing where this is needed. The indentation is also off on lines 221-291 which need one less indent. @Andrea-Havron-NOAA has done a great job explaining the logic of this file in the vignette which was really helpful for our review. It may or may not make sense to add some of this explanation directly in the code as comments to help future developers understand what is being done and why without having to refer back to the vignette or manual.

**Comment by nathanvaughan-NOAA** [comment]
I made a new branch for these changes 407-information-logs

**Comment by nathanvaughan-NOAA** [comment]
@kellijohnson-NOAA  I pushed up new changes with basic logs for CreateModel() can you take a look and let me know if you think anything is missing or should be changed. Everything is going to FIMS_LOG for now, I think we need to figure out a larger plan for how to separate logs for different sections/needs and then we can modify this but not sure that is in the scope of this issue.

**Comment by Andrea-Havron-NOAA** [comment]
@nathanvaughan-NOAA, issue #255 is probably a better issue to address a larger plan for separate log files.

**Comment by nathanvaughan-NOAA** [comment]
Addressed in pull request #424
