### ISSUE TITLE
[Refactor]: Document test-fims-estimation.R

### ISSUE THREAD

**Issue by Andrea-Havron-NOAA** [NOAA-FIMS/FIMS#409]
### Refactor request

More documentation is needed in test-fims-estimation.R

### Expected behavior

- [ ] Document defaults for parameter fields (i.e., value, estimated, is_random_effect)
- [ ] Each module should contain more documentation on parameters available to set in a module, parameter descriptions (e.g., log_Fmort is the log scale instantaneous F)
- [ ] Add libraries in front of external functions (e.g., TMB::MakeADFun, stats::optim)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Andrea-Havron-NOAA** [comment]
Documentation should be added to both the R file and C++ interface file

**Comment by Bai-Li-NOAA** [comment]
Maybe we can use [{testdown}](https://github.com/ThinkR-open/testdown) and roxygen tags to document tests and generate a bookdown report of {testthat} results?
