### ISSUE TITLE
[Refactor]: Revisit naming convention of member and local variables in a class

### ISSUE THREAD

**Issue by Andrea-Havron-NOAA** [NOAA-FIMS/FIMS#411]
### Refactor request

Some classes in C++ have class members and local variables with the same name and is a point of confusion. Currently, FIMS uses `this->` to distinguish between class members and local variables.  An example is in the FleetInterface class in [rcpp_fleet.hpp](https://github.com/NOAA-FIMS/FIMS/blob/main/inst/include/interface/rcpp/rcpp_objects/rcpp_fleet.hpp). `selectivity_id` is a class member of FleetInterface. There is also a function within this class, `SetSelectivity` that has a local variable also named `selectivity_id`. The `SetSelectivity` function assigns the class member based on the value of the local variable:

`this->selectivity_id = selectivity_id
`

The `add_to_fims_tmb()` function in FleetInterface has additional reference to the selectivity_id member of fleet (f0 is a pointer to the fleet module):

 `f0 -> selectivity_id = this->selectivity_id
`

### Expected behavior

The Google C++ style guide naming convections for class members is to include a trailing `_` to help distringuish between class member and local variable names ( The `_` is added to class member). This would update the above examples to:

`selectivity_id_ = selectivity_id
`

 `f0 -> selectivity_id_ = selectivity_id_
`

Would updating our naming conventions to the Google style guide recommendations improve readability?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Andrea-Havron-NOAA** [comment]
Related to Issue #384

**Comment by nathanvaughan-NOAA** [comment]
Maybe we could also add detail about the class to the member names such as fleet_selectivity_id_ and interface_selectivity_id_ as f0 -> selectivity_id_ = selectivity_id_ 
is probably no less confusing than 
this->selectivity_id = selectivity_id 
but these may be more interpretable if they were written as
interface_selectivity_id_ = selectivity_id 
and
f0 -> fleet_selectivity_id_ = interface_selectivity_id_ 
If we are good about keeping these names consistent with the class and file names this would also make it much easier to understand how data are moving around in the code without having to reference back to the code structure documentation.

**Comment by Andrea-Havron-NOAA** [comment]
_m is a C++ style to indicate member while _g indicates global

Proposed update:
```
interface_selectivity_id_m = selectivity_id
fleet_g -> fleet_selectivity_id_m = interface_selectivity_id_m
```
@msupernaw, am I right in thinking the fleet pointer is global?

**Comment by ChristineStawitz-NOAA** [comment]
did we fix this one?

**Comment by Andrea-Havron-NOAA** [comment]
@Bai-Li-NOAA is working on this issue with her group using branch 411-rebase / 411-refactor-revisit-naming-conventions
