### ISSUE TITLE
[Bug]: developer checklist not working as expected

### ISSUE THREAD

**Issue by k-doering-NOAA** [NOAA-FIMS/FIMS#441]
### Describe the bug

The [developer checklist](https://github.com/NOAA-FIMS/FIMS/pull/437#issuecomment-1678048908) is only generated if someone marks a pull request as "ready for review", which does not happen on every pull request.

I think the intention was to have it generated on every pull request, but  looking at the list, I wonder if we want to slim down the checklist (some things are tested by github actions), or do away with it altogether, if we feel like it is not useful.

**Comment by ChristineStawitz-NOAA** [comment]
We should make the trigger when a PR is opened and remove a couple of the checklist items:
1. parallel processing
2. testing items - only relevant for new features

**Comment by k-doering-NOAA** [comment]
merged in...we can refine the the pr checklist as needed
