### ISSUE TITLE
[FEATURE] R function that generates a skeleton for new modules

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS#46]
**Is your feature request related to a problem? Please describe.**
It's difficult to know how to create a module from scratch.

**Describe the solution you'd like**
An `R` function called `make_module("name")` where name is the name of the module. This would create the components of the module needed to run in FIMS which include

- [x] file name.hpp in inst/include/population dynamics
- [x] folder name_modules in inst/include/population_dynamics
- [x] file name_modules in inst/include/population_dynamics/name_modules
- [ ] new code with RCPP_MODULE(name) in interface.hpp
- [ ] (optional) new code in fims_math.hpp that might be shared across population_dynamics
- [ ] code to populate .hpp files with correct template
- [ ] test code for R function
- [ ] test template for new modules
- [ ] cleanup function to delete accidental modules?

**Describe alternatives you've considered**
Current approach is for developers to need to know this.

**Comment by k-doering-NOAA** [comment]
This function could be helpful, if you wanted it to pull files from github (say, committed to the FIMS repo): https://github.com/r-lib/usethis/blob/main/R/use_github_file.R

An example of its use: https://github.com/r-lib/usethis/blob/main/R/use_github_file.R

**Comment by kellijohnson-NOAA** [comment]
We could use code in [usethis::use_src_example_script() and other functions](https://github.com/r-lib/usethis/blob/HEAD/R/rcpp.R) for ideas on what we need.

**Comment by ChristineStawitz-NOAA** [comment]
added in code to create the directory and files. also added in .hpp templates under inst/include/templates

still need to add

- [ ] code to populate .hpp files with correct template
- [ ] test code
- [ ] cleanup function to delete accidental modules?

**Comment by ChristineStawitz-NOAA** [comment]
@msupernaw can you look at the .hpp files in templates?
