### ISSUE TITLE
[Developer Issue]: delete tests of nll objects that no longer exist

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS#471]
### Issue details

We've got tests for some NLL objects AgeCompNLL and IndexNLL where I don't think the objects exist anymore in FIMS. The likelihood calculations are tested with the integrated test.

**Comment by ChristineStawitz-NOAA** [comment]
We deleted the fleet age comp NLL and index NLL tests from `inst/extdata/TMB_tests/distributions`

@k-doering-NOAA pointed out we could make the distribution tests that right now need to be manually run through `test_distributions.R` hooked up to `testthat` - but not clear if we want this? @Andrea-Havron-NOAA what do you think?

**Comment by Andrea-Havron-NOAA** [comment]
The tests in `inst/extdata/TMB_tests/distributions` were written during development to make sure we were setting up FIMS-TMB linkages correctly and were developed before `test_distributions.R`. I think the latter file in testthat serves the same purpose as a unit test on the TMB distributions and can be a replacement to the files in `inst/extdata/TMB_tests/distributions`.

**Comment by ChristineStawitz-NOAA** [comment]
In addition to deleting extdata, I will add the evaluate nll tests to test_fleet_interface and update the pull request
