### ISSUE TITLE
[Question/help] Why is population.spawning_biomass indexed by age in test?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [NOAA-FIMS/FIMS#494]
While working on issue #402 and rebasing the associated branch onto main which included the recently merged #272, @Andrea-Havron-NOAA, @KyleShertzer-NOAA, and I could not understand why the `population.spawning_biomass` is being indexed by year and age and not just year in these lines of a test file 
https://github.com/NOAA-FIMS/FIMS/blob/daf1298ce83cdf16ebc4cb145847f5d18de8795c/tests/gtest/test_population_Recruitment.cpp#L69-L72

We also could figure out where `population.spawning_biomass` comes from.

Those lines were created by the huge "Population loop module" PR https://github.com/NOAA-FIMS/FIMS/pull/237 which squashed 184 commits so it's hard to track down which one added this piece to better understand how it works.

All this suggests that some additional comments in the test file would be helpful for folks to understand why the status-quo setup is correct. Or if not, then it should be changed to be indexed just by year.

**Comment by Bai-Li-NOAA** [comment]
Great catch! The test wasn't registered in CMakeLists.txt, causing CMake to skip it. After registration, the GHA checks failed. You can find the updated test [here](https://github.com/NOAA-FIMS/FIMS/blob/3dbecd32218697b992877f2395b6ada8d3587588/tests/gtest/test_population_Recruitment.cpp), and I've opened a pull request #508 to merge these changes into the main branch.
