### ISSUE TITLE
[BUG] build error in gtest

### ISSUE THREAD

**Issue by msupernaw** [NOAA-FIMS/FIMS#52]
**Describe the bug**
Kind of a cryptic error:
"'\g is not followed by a braced, angle-bracketed, or quoted name/number or by a plain number''

**To Reproduce**

**Expected behavior**

**Screenshots**
 Warning in grepl(e, files, perl = TRUE, ignore.case = TRUE) :
     PCRE pattern compilation error
   	'\g is not followed by a braced, angle-bracketed, or quoted name/number or by a plain number'
   	at 'test'
   Error in grepl(e, files, perl = TRUE, ignore.case = TRUE) : 
     invalid regular expression 'tests\gtest'
   Execution halted
Error: Failed to install 'FIMS' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> * preparing ‘FIMS’:
E> * checking DESCRIPTION meta-information ... OK
E> * cleaning src
E> Warning in grepl(e, files, perl = TRUE, ignore.case = TRUE) :
E>   PCRE pattern compilation error
E> 	'\g is not followed by a braced, angle-bracketed, or quoted name/number or by a plain number'
E> 	at 'test'
E> Error in grepl(e, files, perl = TRUE, ignore.case = TRUE) : 
E>   invalid regular expression 'tests\gtest'
E> Execution halted

**Desktop (please complete the following information):**
 - Mac OS 10.15.7

**Additional context**

**Comment by msupernaw** [comment]
Hi Bai,
Not sure what's changed about the test directory. The feat-information branch installs just fine...

**Comment by Bai-Li-NOAA** [comment]
Hi @msupernaw, the error is related to a typo in a .Rbuildignore file. I added the fix as a new commit in pull request #50 and just merged the PR. Please pull the latest changes from the main branch to your feature branch and let me know if you still see the same error. I expect that r-cmd-check works on macOS, but not windows and Linux.
