### ISSUE TITLE
[Developer Issue]: add gdb and TMBhelper to FIMS codespace JSON

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS#551]
### Issue details

it would be helpful to include gdb and tmbhelper in the .json file for the FIMS devcontainer

**Comment by k-doering-NOAA** [comment]
See related issue: https://github.com/NOAA-FIMS/case-studies/issues/30

**Comment by msupernaw** [comment]
Can we add lldb to the FIMS codespace JSON as well?

**Comment by Bai-Li-NOAA** [comment]
@msupernaw I think Codespaces runs in a Linux environment, and we use Visual Studio Code on Codespaces. [Currently, Visual Studio Code does not support LLDB on Linux](https://code.visualstudio.com/docs/cpp/cpp-debug).

**Comment by kellijohnson-NOAA** [comment]
@ChristineStawitz-NOAA can you inform us why we should add TMBHelper to the codespace?

**Comment by ChristineStawitz-NOAA** [comment]
Adding another chain to this Github issue thread - I opened this in response to this thread when we were debugging case studies. It looks like a number of case studies loaded it, but only @Cole-Monnahan-NOAA 's AFSC GOA pollock case study was actually dependent on the package so maybe he can comment on if we expect users to use `TMBhelper` in a standard FIMS workflow

**Comment by k-doering-NOAA** [comment]
Thanks @ChristineStawitz-NOAA ! I think we now have a codespace within the case studies repo, which does include TMBhelper.

So, maybe this issue could actually be closed, unless those working on FIMS development need gdb and TMBhelper?

**Comment by Cole-Monnahan-NOAA** [comment]
I think we should not include TMBhelper as a dependency. We can take that out of my case study. It has some useful features which I suspect we'll recreate in our own high-level fitting function.

**Comment by k-doering-NOAA** [comment]
Thanks @Cole-Monnahan-NOAA , it seems like no action is needed here.
