### ISSUE TITLE
[Feature]: Make units explicit and convert between units

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS#562]
### Is your feature request related to a problem? Please describe.

Implicit unit specification causes a lot of mistakes and wasted time in stock assessment models

### Describe the solution you would like.

Users should be able to specify units in any standard format and the model code converts appropriately.

### Describe alternatives you have considered

We could also enforce one set of units and make the user do the conversion themselves

**Comment by kellijohnson-NOAA** [comment]
If we allow users to input quantities in multiple units would the output be in the original units or in standard units?

**Comment by ChristineStawitz-NOAA** [comment]
@Bai-Li-NOAA and I discussed this - we'd need to either:

1. convert internally within C++ so all output units are standard
2. do some passing of information from the input interface to the output of what the units are
3. rename quantities within the C++ model to specify units e.g. `catch_mt` vs `catch_kg` such that `ADREPORT` includes some definition of units, as the object name is the only thing in `ADREPORT`

**Comment by kellijohnson-NOAA** [comment]
#561 addressed the lack of documentation on units. #315 also talks about converting units. Conversion might come later on if they are justified but for now FIMS will focus on documenting the units that are used in the model.
