### ISSUE TITLE
[Feature]: separate NLL components by fleet

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/FIMS#575]
### Is your feature request related to a problem? Please describe.

@Cole-Monnahan-NOAA flagged this in his GOA pollock case study, right now the NLLs by fleet are not exported, just the sum across fleets

### Describe the solution you would like.

Export NLL totals for each fleet directly

### Describe alternatives you have considered

Currently, we output the summed NLL

**Comment by iantaylor-NOAA** [comment]
The R output design document includes likelihood associated with each each observation in the `fit` table:
https://docs.google.com/document/d/1n-3D_ywHhmPNITMU6Jjsh7D1ixYc_CcvckKfdPWBGDM/edit?pli=1#heading=h.ghe64oz7zkw
These could then be aggregated by fleet or whatever other grouping is needed within helper functions after output.

Therefore any changes to what is returned directly by the FIMS function should focus on likelihoods at the observation level, not by fleet or other higher level grouping.

**Comment by Andrea-Havron-NOAA** [comment]
Ou plan is to return observation level log-likelihoods to each Rcpp module. These would then be accessible from R after the model is run.

**Comment by Andrea-Havron-NOAA** [comment]
- [ ] need finalize section in rcpp_distributions to report our log_likelihood_vec

**Comment by Andrea-Havron-NOAA** [comment]
@msupernaw, this issue needs to be completed in such a way that it matches up to the JSON format for output.

**Comment by Andrea-Havron-NOAA** [comment]
close with PR #669
