### ISSUE TITLE
[Developer Issue]: are use_module() and create_rcpp_interface_object() being used?

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [NOAA-FIMS/FIMS#588]
### Issue details

I am wondering if `use_module()` and `create_rcpp_interface_object()` are being used by anyone? They are both developer functions rather than user functions so it makes sense that they are not in the code base but given the limited scope/functionality of `use_module()` I think it should be removed. @msupernaw is `create_rcpp_interface_object()` up to date because I know it was created a while ago?

At a minimum, I think that these functions, if kept, should not be exported.

**Comment by Andrea-Havron-NOAA** [comment]
@nathanvaughan-NOAA, do you see any use in the `use_module` function for your more features group during M2? I can go either way on removing or keeping it. I am pretty sure the `create_rcpp_interface_object()` function is out of date.

**Comment by nathanvaughan-NOAA** [comment]
I would agree it's a pretty safe bet that both are out of date. They are both part of our goal of automating the boilerplate for module development right? Unless there is already other code providing this functionality I would leave them in so we have them as a starting point in the future when we have time to actually develop this fully. I agree we should take them off the export list for now given that they probably don't work as is.

**Comment by Andrea-Havron-NOAA** [comment]
I think if we don't plan to actively use them in M2 development, we should remove them. We could also create issues related to further developing each script and linking the old files to the issue so they are easily found again.

**Comment by nathanvaughan-NOAA** [comment]
Good point @kellijohnson-NOAA. Since none of our groups are going to use them it sounds fine to remove them.

**Comment by kellijohnson-NOAA** [comment]
Okay, I was going to delete them, then I realized that usethis is now only being used in the data-raw folder and not in any functions. So, can I move usethis to a suggested package rather than an import? I am confused because the following line of code could depend on usethis but I am not really sure?
https://github.com/NOAA-FIMS/FIMS/blob/fe5836b9d3cca703f7037ebce70d59dc2134c261/R/FIMS-package.R#L1
@Andrea-Havron-NOAA HELP!

**Comment by Andrea-Havron-NOAA** [comment]
I'm not really sure what `## usethis namespace: start` does. Could that be there because we initialized the namespace using the usethis package? I would try removing line 1 in FIMS-package.R and move `usethis` to `Suggests` and try running `devtools::check()` locally. It will throw an error if one of these changes is incorrect.

**Comment by kellijohnson-NOAA** [comment]
Thanks for the 🏆 suggestion @Andrea-Havron-NOAA. I will try just moving the package to suggests first and push it to a branch to see if anything errors out or gives a warning.
