### ISSUE TITLE
[Developer Issue]: GHA: call-doc-and-style-r workflow failed to run due to SAML single sign-on

### ISSUE THREAD

**Issue by Bai-Li-NOAA** [NOAA-FIMS/FIMS#598]
### Issue details

The call-doc-and-style-r workflow on the main branch [failed to run](https://github.com/NOAA-FIMS/FIMS/actions/runs/9083719043/job/25008903226#step:19:101). Below is the error message:
```github
 /usr/bin/git push --force-with-lease origin style-doc-code:refs/heads/style-doc-code
  remote: The 'NOAA-FIMS' organization has enabled or enforced SAML SSO.
  remote: To access this repository, visit https://github.com/enterprises/noaa-nmfs/sso?authorization_request=ALNPO3PGFKE6KW5D24L53FTGITSCZA5PN5ZGOYLONF5GC5DJN5XF62LEZYCMFSZ4VVRXEZLEMVXHI2LBNRPWSZGOJLMRFZFPMNZGKZDFNZ2GSYLML52HS4DFVNHWC5LUNBAWGY3FONZQ and try your request again.
  fatal: unable to access 'https://github.com/NOAA-FIMS/FIMS/': The requested URL returned error: 403
  Error: The process '/usr/bin/git' failed with exit code 128
```
Do we need @ChristineStawitz-NOAA or @Andrea-Havron-NOAA to enable the token for the NOAA-FIMS org? For example, go into the [personal access token settings](https://github.com/settings/tokens) -> choose "Tokens (classic)" -> generate new token -> choose "Configure SSO" to let NOAA-FIMS org to be authorized for access?

**Comment by ChristineStawitz-NOAA** [comment]
@Bai-Li-NOAA I just authorized the token, please let me know if that fixed it!
