### ISSUE TITLE
Make the R tests more modular

### ISSUE THREAD

**Issue by Bai-Li-NOAA** [NOAA-FIMS/FIMS#606]
The one question that this PR #591 raises for me is whether there's a way to make the tests more modular. That is, the new "agecomp in proportion works" test added to test-integration-fims-estimation.R has a lot of redundancy with the existing "estimation test of fims". We want to make sure proportions still pass all the same checks but the duplicate code would be harder to maintain than if there's some way to wrap it in a function without losing the ability to get detailed output from each element of the test. Having said that, I don't think it makes sense to spend more time on this now, rather to think about the issue for future revisions to the tests.

_Originally posted by @iantaylor-NOAA in https://github.com/NOAA-FIMS/FIMS/pull/591#pullrequestreview-2083992243_

**Comment by Bai-Li-NOAA** [comment]
Thanks, @iantaylor-NOAA. That's a great suggestion, and it is possible to make the tests more modular. I have been testing this in a different branch by 

- Adding test data to the [test fixtures folder](https://github.com/NOAA-FIMS/FIMS/tree/4d1e9ebe5dce59ff3606999c0e434724e9475917/tests/testthat/fixtures)
- Creating some [helper functions](https://github.com/NOAA-FIMS/FIMS/blob/4d1e9ebe5dce59ff3606999c0e434724e9475917/tests/testthat/helper-integration-tests-setup.R) to set up the FIMS model and validate FIMS results with simulated test data

The changes have resulted in much shorter test file (e.g., [test-integration-fleet-log-obs-error-input.R](https://github.com/NOAA-FIMS/FIMS/blob/4d1e9ebe5dce59ff3606999c0e434724e9475917/tests/testthat/test-integration-fleet-log-obs-error-input.R)). I can refactor all integration tests after merging in the test-obs-error-input branch.

**Comment by kellijohnson-NOAA** [comment]
@Bai-Li-NOAA thanks for working on this. Do you think that the test data should probably be added to the repository as a data object where your script to generate the data could be placed in data-raw and `usethis::use_data()` could be used to place the data object in the correct location.

**Comment by Bai-Li-NOAA** [comment]
@kellijohnson-NOAA Good question! It depends on whether we want to distribute the test data to users. If a data object  is generated from an R script in the data-raw/ folder, it will be accessible to users. For test data, I think users don't need access. Therefore,  we can use test fixtures within the {testthat} framework. See the file structure figure in the R Packages (2e) book [here](https://r-pkgs.org/testing-advanced.html#sec-testing-advanced-concrete-fixture).

**Comment by kellijohnson-NOAA** [comment]
Looks great, thanks for the link 👍!
