### ISSUE TITLE
[feature:] Warnings and Notes from R CMD check

### ISSUE THREAD

**Issue by arni-magnusson** [NOAA-FIMS/FIMS#671]
### Describe the situation that led to the request and a solution

I'm wondering if the number of Warnings and Notes from R CMD check could be reduced. This could make it easier for developers/contributors to see when new code introduces relevant warnings or notes.

### Additional context

As of 2 Oct 2024, these are the results of R CMD check on the main branch:

* checking C++ specification ... NOTE
```
  Specified C++11: please drop specification unless essential
```

* checking installed package size ... NOTE
```
  installed size is 53.1Mb
```

* checking dependencies in R code ... NOTE
```
Namespace in Imports field not imported from: ‘scales’
```
* checking for missing documentation entries ... WARNING
```
Undocumented code objects:
  ‘AgeComp’ ‘BevertonHoltRecruitment’ ‘CreateTMBModel’
  ‘DoubleLogisticSelectivity’ ‘EWAAgrowth’ ‘Fleet’ ‘Index’
  ‘LogisticMaturity’ ‘LogisticSelectivity’ ‘Parameter’ ‘Population’
  ‘TMBDlnormDistribution’ ‘TMBDmultinomDistribution’
  ‘TMBDnormDistribution’ ‘clear’ ‘clear_logs’ ‘get_fixed’ ‘get_random’
All user-level objects in a package should have documentation entries.
```
* checking compilation flags in Makevars ... WARNING
```
Non-portable flags in variable 'PKG_CXXFLAGS':
  -w
```
* checking compiled code ... WARNING
```
File ‘FIMS/libs/FIMS.so’:
  Found ‘_ZSt4cout’, possibly from ‘std::cout’ (C++)
    Object: ‘FIMS.o’
  Found ‘exit’, possibly from ‘exit’ (C)
    Object: ‘FIMS.o’
Compiled code should not call entry points which might terminate R nor write to
stdout/stderr instead of to the console, nor use Fortran I/O nor system RNGs nor
[v]sprintf.
See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.
```
Status: 3 WARNINGs, 3 NOTEs

**Comment by kellijohnson-NOAA** [comment]
Thank you @arni-magnusson for this. Much of it, but not all (see [comment in 692](https://github.com/NOAA-FIMS/FIMS/pull/692#issuecomment-2521697878) for comments on things that still need attention). All except the size of the package is set to be fixed soon 💪.
