### ISSUE TITLE
Fill in missing info in the DESCRIPTION file

### ISSUE THREAD

**Issue by k-doering-NOAA** [NOAA-FIMS/FIMS#69]
Title, Description, and Authors are currently missing. It would be great to fill these in to properly document the FIMS package.

Here is an [example DESCRIPTION file (ss3sim)](https://github.com/ss3sim/ss3sim/blob/main/DESCRIPTION)

**Comment by k-doering-NOAA** [comment]
@ChristineStawitz-NOAA I started this in #77; feel free to close if this isn't helpful.

**Comment by ChristineStawitz-NOAA** [comment]
merged in via pr #77
