### ISSUE TITLE
Set up testing system on the FIMS repository

### ISSUE THREAD

**Issue by Andrea-Havron-NOAA** [NOAA-FIMS/FIMS#7]
@k-doering-NOAA and I can work on 

- [x] setting up the testing system (e.g., include the files and folders needed) on the FIMS repository
- [x] getting the testing system running on GitHub actions
- [x] adding [C++ files](https://github.com/Bai-Li-NOAA/TestingExamples/blob/main/.gitignore) to the current .gitignore file
- [x] modifying the GH Actions workflow to save artifacts if a job fails

_Originally posted by @Bai-Li-NOAA in https://github.com/NOAA-FIMS/FIMS/issues/3#issuecomment-1049300604_

**Comment by Bai-Li-NOAA** [comment]
@k-doering-NOAA , I realized that the Google Test folder structure is different compared to the examples I showed to the group in the past, so I went ahead and created the GH actions workflow for FIMS, but definitely will invite you to review all the changes. Thanks!

**Comment by k-doering-NOAA** [comment]
Great! Happy to review as needed :)
