### ISSUE TITLE
[FEATURE] use tool to style c++ code automatically

### ISSUE THREAD

**Issue by k-doering-NOAA** [NOAA-FIMS/FIMS#72]
**Is your feature request related to a problem? Please describe.**
We have styler to style R code, but do not yet use a tool to automatically style c++ code so that we have consistent indents, whitespace, etc.

**Describe the solution you'd like**
It would be great to define a tool to use to style c++ code automatically. One possibility is [Clang format](https://clang.llvm.org/docs/ClangFormat.html).

It would be great to 
-  [ ] Get clang format (or other tool) workling locally
-  [ ] Decide on a consistent C++ style with the tool to format to
-  [ ] Document how to use the tool in the collaboration guide.
-  [x] Format the codebase all at once when there is little active development and submit as in its own pull request
-  [x] Set up a github action to automatically format the codebase. on a schedule or on pushes to main (much like the current doc and style workflow).

**Describe alternatives you've considered**
I'm not sure what other tools our available for styling c++ code.

**Describe a reference describing the statistical validity of this approach**
N/A

**Describe if this is needed for a management application**
N/a

**Additional context**
Note that we have a clang-tidy workflow, but this just does some checks for common coding issues and does not automatically style code.

**Comment by Bai-Li-NOAA** [comment]
I created a branch [feat-issue-72-style-c++-code](https://github.com/NOAA-FIMS/FIMS/tree/feat-issue-72-style-c%2B%2B-code) and happy to modify [clang-format-lint.yml](https://github.com/google/benchmark/blob/main/.github/workflows/clang-format-lint.yml) from Google if both of you have not started working on this issue.

**Comment by k-doering-NOAA** [comment]
That would be great if you put it together, @Bai-Li-NOAA ! I have not worked on it at all. That is great there is already an action to use!

**Comment by Bai-Li-NOAA** [comment]
Some updates:
- I have not been able to install clang-format locally
- The [run-clang-format.yml](https://github.com/NOAA-FIMS/FIMS/blob/feat-issue-72-style-c%2B%2B-code/.github/workflows/run-clang-format.yml) formats the C++ code using Google style (open to other suggestions!). It is much like the current doc and style workflow.

**Comment by ChristineStawitz-NOAA** [comment]
nice find Kathryn, and great job getting it working Bai!
