### ISSUE TITLE
[BUG] call-doc-and-style-r GHA does not work

### ISSUE THREAD

**Issue by Bai-Li-NOAA** [NOAA-FIMS/FIMS#84]
**Describe the bug**
The call-doc-and-style-r GHA failed and returned the error below:
```
Error: Error: unexpected '{' in "if(any(is.na(results[["changed"]])) {"
Execution halted
Error: Process completed with exit code 1.
```

**To Reproduce**
Please see the GHA log [here](https://github.com/NOAA-FIMS/FIMS/runs/6116206870?check_suite_focus=true)

**Expected behavior**
I expect the GHA to pass because there was no styling error based on the output table. 

**Screenshots**
None. 

**Desktop (please complete the following information):**
 - Windows

**Additional context**

**Comment by k-doering-NOAA** [comment]
Thanks, Bai! I think there was a missing ) (oops!). I hope [c3e05f5](https://github.com/nmfs-fish-tools/ghactions4r/commit/c3e05f5f6ec018e9d6d5a57d7c6d5d8ea5a4364c) that I pushed this morning fixes it, so I restarted the FIMS github action- I will close if it passes!

**Comment by k-doering-NOAA** [comment]
Hmm, call-doc-and-style still isn't passing, but gets past the issue: https://github.com/NOAA-FIMS/FIMS/runs/6134030761?check_suite_focus=true

Now, it doesn't work because FIMS can't compile on ubuntu.

If we wanted to run it in the meantime, we could change to using mac as the runner instead.

**Comment by k-doering-NOAA** [comment]
closing for now, and opened #85 to discuss the FIMS compilation issue. Feel free to reopen if needed.
