### ISSUE TITLE
[BUG]: TMB bug stops FIMS from compiling on Linux and Windows

### ISSUE THREAD

**Issue by k-doering-NOAA** [NOAA-FIMS/FIMS#85]
**Describe the bug**
A bug in TMB prevents from FIMS from compiling on Windows and Mac. I know that the team knows this and that @msupernaw and @Bai-Li-NOAA contacted TMB folks to ask for a fix, but I'm not sure how to go about getting FIMS to compile

**To Reproduce**
In an R console on Windows or Linux in a clone of the FIMS repo, run devtools::check(). The check will fail.

**Expected behavior**
devtools::check() works, as does devtools::install_github("NOAA-FIMS/FIMS").

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows, Ubuntu
 - Browser [e.g. chrome, safari] n/a

**Additional context**
Potential solutions - has the fix been made on the github version of tmb? If so, I suggest we switch to using that version temporarily. The only change that would need to be made is specifying the path to the github version of FIMS in a section called `Remotes` in the `DESCRIPTION` file, e.g., : https://github.com/ss3sim/ss3sim/blob/fe8ba9ae059a46b43d835bfb197cea4659d6749f/DESCRIPTION#L58

**Comment by ChristineStawitz-NOAA** [comment]
Thanks @k-doering-NOAA . I think @Bai-Li-NOAA had a fix for this which involved simply including cmath after TMB so that the isNAN in cmath masks the TMB function. Andrea and I looked at the code the other day and I couldn't quite figure out where to swap the include statements though.

**Comment by ChristineStawitz-NOAA** [comment]
Thanks @Bai-Li-NOAA I opened a PR because I think the ubuntu error is totally unrelated to this..although if anyone knows how to fix that we can push it to the PR!
