### ISSUE TITLE
Cleanup README - add badges and fit init.h issue

### ISSUE THREAD

**Issue by k-doering-NOAA** [NOAA-FIMS/FIMS#90]
I've come across a couple additional checks that are required before submitting to [rOpenSci](https://stats-devguide.ropensci.org/pkgdev.html):

1. pkgcheck() from the pkgcheck library
2. autotest_package() from the autotest library

We may or may not want/need to submit FIMS to rOpenSci, but the checks are still useful in detecting potential problems or inefficiencies in a package.

_Originally posted by @Andrea-Havron-NOAA in https://github.com/NOAA-FIMS/FIMS/issues/55#issuecomment-1095290354_

**Comment by Bai-Li-NOAA** [comment]
I've checked autotest_package() from the [autotest](https://docs.ropensci.org/autotest/articles/autotest.html) library. 
- It runs the tests under the testthat folder
- It checks if a file needs a test by scraping documented examples from all .Rd files (not all R files).  
- The results would be NULL if all tests pass. The output indicated that FIMS::mkObj() needs a test.
```
-- autotesting FIMS --

v [1 / 1]: mkObj
```

Currently, we use devtools::test() for FIMS.
- devtools::test() runs the tests under the testthat folder. 
- devtools::test_coverage() computes test coverage for the package by scraping all files under R/ and src/. (Maybe we can add the coverage table to FIMS readme?)
- test_coverage() returns a summary table and an interactive report that shows which lines of the code need a test.

```
FIMS Coverage: 27.78%
R/io.R: 0.00%
R/zzz.R: 0.00%
src/FIMS.cpp: 0.00%
src/init.hpp: 100.00%
```
At this moment, devtools::test() and autotest_package() give very similar feedback. Could check the two functions again when we have more R code in the repo.

@Andrea-Havron-NOAA, I am not able to install pkgcheck through CRAN (R version issue) or GitHub (dependency issue). It would be great if you have time to take a look at the pkgcheck and compare the summary of check results between CRAN devtools::check() and pkgcheck. Thanks!

**Comment by k-doering-NOAA** [comment]
These are all great ideas!THanks @Andrea-Havron-NOAA and @Bai-Li-NOAA for looking into this.

I've never set up code coverage for an R package that has C++ code; I'm curious if there is a way for us to set it up so we get "credit" for the coverage of the google tests? Or maybe this already an option that I'm just not aware of.

**Comment by ChristineStawitz-NOAA** [comment]
I think the new README looks great @Andrea-Havron-NOAA  ! Thank you!

**Comment by Andrea-Havron-NOAA** [comment]
@Bai-Li-NOAA and @ChristineStawitz-NOAA,

I commented out the std::cout code in the Interface.hpp file and re-ran R CMD check. This removed the note:
`> checking compiled code ... NOTE
  File 'FIMS/libs/i386/FIMS.dll':
    Found '_ZSt4cout', possibly from 'std::cout' (C++)
      Object: 'FIMS.o'
  File 'FIMS/libs/x64/FIMS.dll':
    Found '_ZSt4cout', possibly from 'std::cout' (C++)
      Object: 'FIMS.o'`
 
So it does look like it is our code throwing this issue and is not related to the recent TMB release.

From my understanding, this is just placeholder code and the final version of FIMS will not use any std::cout statements. If that is correct, we can leave the std::cout code as is and ignore this note for now.

**Comment by Bai-Li-NOAA** [comment]
@Andrea-Havron-NOAA , I also think the std::cout code in the Interface.hpp file is just placeholder code and we can ignore this note for now. 

I reopened the issue because we have some unfinished tasks. I am working on linking codecov with C++ tests. 

We may need help from @msupernaw to add more doxygen documentation for a few files.

**Comment by Bai-Li-NOAA** [comment]
When generating doxygen htmls locally, we got more warnings. Please see [all the warnings under Building HTML documentation with Doxygen section](https://github.com/NOAA-FIMS/FIMS/runs/6731241079?check_suite_focus=true#step:6:93). @msupernaw, could you add documentation in interface.hpp, FIMS.cpp, def.hpp, and files under rcpp/rcpp_objects? Thanks!
